return {
		[1000] = "其他错误",
    ERR_OTHER = 1000,
		[0] = "成功",
	SUCCESS = 0,
		[1] = "密码错误",
	WRONG_PWD = 1,
		[2] = "服务器连接失败",
	SERVER_CONN_FAILED = 2,
		[3] = "服务器错误结束",
	SERVER_EXCEPTION = 3,
		[4] = "房间创建失败",
	CREATE_ROOM_FAILED = 4,
		[5] = "房间人数已满",
	JOIN_ROOM_FAILED_FULL = 5,
		[6] = "房间不存在",
	JOIN_ROOM_FAILED_NOT_EXISTS = 6,
		[7] = "没有可用房间",
	NO_AVAILABLE_ROOM_SERVER = 7,
		[8] = "动作不可用",
	UNAVAILAVLE_ACTION = 8,
		[9] = "非法操作",
	ILLEGAL_OP = 9,
}