--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create spBg
local spBg = cc.Sprite:create("public/bg-chongxinglianjie.png")
spBg:setName("spBg")
spBg:setTag(224)
spBg:setCascadeColorEnabled(true)
spBg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(spBg)
layout:setSize({width = 705.0000, height = 41.0000})
layout:setLeftMargin(-23.0000)
layout:setRightMargin(-23.0000)
layout:setTopMargin(-23.0000)
layout:setBottomMargin(-23.0000)
spBg:setBlendFunc({src = 1, dst = 771})
Node:addChild(spBg)

--Create lblTip
local lblTip = ccui.Text:create()
lblTip:ignoreContentAdaptWithSize(true)
lblTip:setTextAreaSize({width = 0, height = 0})
lblTip:setFontName("font/DFYuanW7-GB2312.ttf")
lblTip:setFontSize(36)
lblTip:setString([[Tip]])
lblTip:setLayoutComponentEnabled(true)
lblTip:setName("lblTip")
lblTip:setTag(225)
lblTip:setCascadeColorEnabled(true)
lblTip:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(lblTip)
layout:setSize({width = 52.0000, height = 36.0000})
layout:setLeftMargin(-26.5000)
layout:setRightMargin(-26.5000)
layout:setTopMargin(-19.0000)
layout:setBottomMargin(-19.0000)
Node:addChild(lblTip)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

