--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorOpacity(140)
panRoot:setTouchEnabled(true);
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(848)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
panRoot:setPosition(0.0000, -1.4015)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setPositionPercentY(-0.0019)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setTopMargin(1.4015)
layout:setBottomMargin(-1.4015)
Layer:addChild(panRoot)

--Create imgBg
local imgBg = ccui.ImageView:create()
imgBg:ignoreContentAdaptWithSize(false)
imgBg:loadTexture("public/bf-tonyongkuang.png",0)
imgBg:setTouchEnabled(true);
imgBg:setLayoutComponentEnabled(true)
imgBg:setName("imgBg")
imgBg:setTag(840)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(649.7853, 356.4117)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentX(0.5076)
layout:setPositionPercentY(0.4950)
layout:setPercentWidth(0.5695)
layout:setPercentHeight(0.6431)
layout:setSize({width = 729.0000, height = 463.0000})
layout:setLeftMargin(285.2853)
layout:setRightMargin(265.7147)
layout:setTopMargin(132.0883)
layout:setBottomMargin(124.9117)
Layer:addChild(imgBg)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("public/bf-tongyong3.png",0)
Image_2:setScale9Enabled(true)
Image_2:setCapInsets({x = 19, y = 64, width = 122, height = 32})
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(841)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(364.6025, 230.8880)
Image_2:setScaleX(1.0372)
Image_2:setScaleY(1.0526)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.4987)
layout:setPercentWidth(0.9053)
layout:setPercentHeight(0.8704)
layout:setSize({width = 660.0000, height = 403.0000})
layout:setLeftMargin(34.6025)
layout:setRightMargin(34.3975)
layout:setTopMargin(30.6120)
layout:setBottomMargin(29.3880)
imgBg:addChild(Image_2)

--Create panLayout
local panLayout = ccui.Layout:create()
panLayout:ignoreContentAdaptWithSize(false)
panLayout:setBackGroundImage("public/bf-tongyong4.png",0)
panLayout:setClippingEnabled(false)
panLayout:setBackGroundImageCapInsets({x = 110, y = 25, width = 116, height = 28})
panLayout:setBackGroundColorOpacity(102)
panLayout:setBackGroundImageScale9Enabled(true)
panLayout:setTouchEnabled(true);
panLayout:setLayoutComponentEnabled(true)
panLayout:setName("panLayout")
panLayout:setTag(843)
panLayout:setCascadeColorEnabled(true)
panLayout:setCascadeOpacityEnabled(true)
panLayout:setPosition(80.1743, 95.2707)
layout = ccui.LayoutComponent:bindLayoutComponent(panLayout)
layout:setPositionPercentX(0.1100)
layout:setPositionPercentY(0.2058)
layout:setPercentWidth(0.7737)
layout:setPercentHeight(0.5767)
layout:setSize({width = 564.0000, height = 267.0000})
layout:setLeftMargin(80.1743)
layout:setRightMargin(84.8257)
layout:setTopMargin(100.7293)
layout:setBottomMargin(95.2707)
imgBg:addChild(panLayout)

--Create btnFriends
local btnFriends = ccui.Button:create()
btnFriends:ignoreContentAdaptWithSize(false)
btnFriends:loadTextureNormal("HomeScene/wechatShare/bt-weixing.png",0)
btnFriends:loadTexturePressed("HomeScene/wechatShare/bt-weixing.png",0)
btnFriends:loadTextureDisabled("HomeScene/wechatShare/bt-weixing.png",0)
btnFriends:setTitleFontName("font/DFYuanW7-GB2312.ttf")
btnFriends:setTitleFontSize(36)
btnFriends:setLayoutComponentEnabled(true)
btnFriends:setName("btnFriends")
btnFriends:setTag(844)
btnFriends:setCascadeColorEnabled(true)
btnFriends:setCascadeOpacityEnabled(true)
btnFriends:setPosition(158.2750, 162.0652)
layout = ccui.LayoutComponent:bindLayoutComponent(btnFriends)
layout:setPositionPercentX(0.2806)
layout:setPositionPercentY(0.6070)
layout:setPercentWidth(0.2411)
layout:setPercentHeight(0.5131)
layout:setSize({width = 136.0000, height = 137.0000})
layout:setLeftMargin(90.2750)
layout:setRightMargin(337.7250)
layout:setTopMargin(36.4348)
layout:setBottomMargin(93.5652)
panLayout:addChild(btnFriends)

--Create Text_6
local Text_6 = ccui.Text:create()
Text_6:ignoreContentAdaptWithSize(true)
Text_6:setTextAreaSize({width = 0, height = 0})
Text_6:setFontName("font/DFYuanW7-GB2312.ttf")
Text_6:setFontSize(36)
Text_6:setString([[好友/群]])
Text_6:setLayoutComponentEnabled(true)
Text_6:setName("Text_6")
Text_6:setTag(927)
Text_6:setCascadeColorEnabled(true)
Text_6:setCascadeOpacityEnabled(true)
Text_6:setAnchorPoint(0.6163, 0.3731)
Text_6:setPosition(172.7407, 43.4287)
Text_6:setTextColor({r = 38, g = 20, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_6)
layout:setPositionPercentX(0.3063)
layout:setPositionPercentY(0.1627)
layout:setPercentWidth(0.2270)
layout:setPercentHeight(0.1536)
layout:setSize({width = 128.0000, height = 41.0000})
layout:setLeftMargin(93.8543)
layout:setRightMargin(342.1457)
layout:setTopMargin(197.8684)
layout:setBottomMargin(28.1316)
panLayout:addChild(Text_6)

--Create btnMoments
local btnMoments = ccui.Button:create()
btnMoments:ignoreContentAdaptWithSize(false)
btnMoments:loadTextureNormal("HomeScene/wechatShare/bg-penyouquang.png",0)
btnMoments:loadTexturePressed("HomeScene/wechatShare/bg-penyouquang.png",0)
btnMoments:loadTextureDisabled("HomeScene/wechatShare/bg-penyouquang.png",0)
btnMoments:setTitleFontName("font/DFYuanW7-GB2312.ttf")
btnMoments:setTitleFontSize(36)
btnMoments:setLayoutComponentEnabled(true)
btnMoments:setName("btnMoments")
btnMoments:setTag(846)
btnMoments:setCascadeColorEnabled(true)
btnMoments:setCascadeOpacityEnabled(true)
btnMoments:setPosition(406.2119, 162.0652)
layout = ccui.LayoutComponent:bindLayoutComponent(btnMoments)
layout:setPositionPercentX(0.7202)
layout:setPositionPercentY(0.6070)
layout:setPercentWidth(0.2411)
layout:setPercentHeight(0.5131)
layout:setSize({width = 136.0000, height = 137.0000})
layout:setLeftMargin(338.2119)
layout:setRightMargin(89.7881)
layout:setTopMargin(36.4348)
layout:setBottomMargin(93.5652)
panLayout:addChild(btnMoments)

--Create Text_6_0
local Text_6_0 = ccui.Text:create()
Text_6_0:ignoreContentAdaptWithSize(true)
Text_6_0:setTextAreaSize({width = 0, height = 0})
Text_6_0:setFontName("font/DFYuanW7-GB2312.ttf")
Text_6_0:setFontSize(36)
Text_6_0:setString([[朋友圈]])
Text_6_0:setLayoutComponentEnabled(true)
Text_6_0:setName("Text_6_0")
Text_6_0:setTag(928)
Text_6_0:setCascadeColorEnabled(true)
Text_6_0:setCascadeOpacityEnabled(true)
Text_6_0:setPosition(411.3950, 48.6334)
Text_6_0:setTextColor({r = 38, g = 20, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_6_0)
layout:setPositionPercentX(0.7294)
layout:setPositionPercentY(0.1821)
layout:setPercentWidth(0.1915)
layout:setPercentHeight(0.1536)
layout:setSize({width = 108.0000, height = 41.0000})
layout:setLeftMargin(357.3950)
layout:setRightMargin(98.6050)
layout:setTopMargin(197.8666)
layout:setBottomMargin(28.1334)
panLayout:addChild(Text_6_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

