--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create rootPanel
local rootPanel = ccui.Layout:create()
rootPanel:ignoreContentAdaptWithSize(false)
rootPanel:setClippingEnabled(false)
rootPanel:setBackGroundColorOpacity(102)
rootPanel:setTouchEnabled(true);
rootPanel:setLayoutComponentEnabled(true)
rootPanel:setName("rootPanel")
rootPanel:setTag(225)
rootPanel:setCascadeColorEnabled(true)
rootPanel:setCascadeOpacityEnabled(true)
rootPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(rootPanel)
layout:setSize({width = 54.0000, height = 100.0000})
layout:setLeftMargin(-27.0000)
layout:setRightMargin(-27.0000)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
Node:addChild(rootPanel)

--Create img11
local img11 = ccui.ImageView:create()
img11:ignoreContentAdaptWithSize(false)
img11:loadTexture("GameScene/left/mingmah_00.png",0)
img11:setLayoutComponentEnabled(true)
img11:setName("img11")
img11:setTag(226)
img11:setCascadeColorEnabled(true)
img11:setCascadeOpacityEnabled(true)
img11:setPosition(27.6666, 77.0498)
layout = ccui.LayoutComponent:bindLayoutComponent(img11)
layout:setPositionPercentX(0.5123)
layout:setPositionPercentY(0.7705)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4800)
layout:setSize({width = 54.0000, height = 48.0000})
layout:setLeftMargin(0.6666)
layout:setRightMargin(-0.6666)
layout:setTopMargin(-1.0498)
layout:setBottomMargin(53.0498)
rootPanel:addChild(img11)

--Create img12
local img12 = ccui.ImageView:create()
img12:ignoreContentAdaptWithSize(false)
img12:loadTexture("GameScene/left/mingmah_00.png",0)
img12:setLayoutComponentEnabled(true)
img12:setName("img12")
img12:setTag(227)
img12:setCascadeColorEnabled(true)
img12:setCascadeOpacityEnabled(true)
img12:setPosition(27.1019, 48.6779)
layout = ccui.LayoutComponent:bindLayoutComponent(img12)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.4868)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4800)
layout:setSize({width = 54.0000, height = 48.0000})
layout:setLeftMargin(0.1019)
layout:setRightMargin(-0.1019)
layout:setTopMargin(27.3221)
layout:setBottomMargin(24.6779)
rootPanel:addChild(img12)

--Create img13
local img13 = ccui.ImageView:create()
img13:ignoreContentAdaptWithSize(false)
img13:loadTexture("GameScene/left/mingmah_00.png",0)
img13:setLayoutComponentEnabled(true)
img13:setName("img13")
img13:setTag(228)
img13:setCascadeColorEnabled(true)
img13:setCascadeOpacityEnabled(true)
img13:setPosition(27.1018, 19.9847)
layout = ccui.LayoutComponent:bindLayoutComponent(img13)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.1998)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4800)
layout:setSize({width = 54.0000, height = 48.0000})
layout:setLeftMargin(0.1018)
layout:setRightMargin(-0.1018)
layout:setTopMargin(56.0153)
layout:setBottomMargin(-4.0153)
rootPanel:addChild(img13)

--Create img21
local img21 = ccui.ImageView:create()
img21:ignoreContentAdaptWithSize(false)
img21:loadTexture("GameScene/left/mingmah_00.png",0)
img21:setLayoutComponentEnabled(true)
img21:setName("img21")
img21:setTag(229)
img21:setCascadeColorEnabled(true)
img21:setCascadeOpacityEnabled(true)
img21:setPosition(27.2575, 63.7321)
layout = ccui.LayoutComponent:bindLayoutComponent(img21)
layout:setPositionPercentX(0.5048)
layout:setPositionPercentY(0.6373)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4800)
layout:setSize({width = 54.0000, height = 48.0000})
layout:setLeftMargin(0.2575)
layout:setRightMargin(-0.2575)
layout:setTopMargin(12.2679)
layout:setBottomMargin(39.7321)
rootPanel:addChild(img21)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

