--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img1
local img1 = ccui.ImageView:create()
img1:ignoreContentAdaptWithSize(false)
img1:loadTexture("GameScene/bt-dinglai1.png",0)
img1:setLayoutComponentEnabled(true)
img1:setName("img1")
img1:setTag(190)
img1:setCascadeColorEnabled(true)
img1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img1)
layout:setSize({width = 294.0000, height = 280.0000})
layout:setLeftMargin(-147.0000)
layout:setRightMargin(-147.0000)
layout:setTopMargin(-140.0000)
layout:setBottomMargin(-140.0000)
Node:addChild(img1)

--Create img2
local img2 = ccui.ImageView:create()
img2:ignoreContentAdaptWithSize(false)
img2:loadTexture("GameScene/bt-dinglai2.png",0)
img2:setLayoutComponentEnabled(true)
img2:setName("img2")
img2:setTag(191)
img2:setCascadeColorEnabled(true)
img2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img2)
layout:setSize({width = 378.0000, height = 145.0000})
layout:setLeftMargin(-189.0000)
layout:setRightMargin(-189.0000)
layout:setTopMargin(-72.5000)
layout:setBottomMargin(-72.5000)
Node:addChild(img2)

--Create imgCard
local imgCard = ccui.ImageView:create()
imgCard:ignoreContentAdaptWithSize(false)
imgCard:loadTexture("GameScene/vertical/mingmah_39.png",0)
imgCard:setLayoutComponentEnabled(true)
imgCard:setName("imgCard")
imgCard:setTag(192)
imgCard:setCascadeColorEnabled(true)
imgCard:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard)
layout:setSize({width = 89.0000, height = 135.0000})
layout:setLeftMargin(-44.5000)
layout:setRightMargin(-44.5000)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(-67.5000)
Node:addChild(imgCard)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

