--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorType(1)
panRoot:setBackGroundColor({r = 0, g = 0, b = 0})
panRoot:setBackGroundColorOpacity(127)
panRoot:setTouchEnabled(true);
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(601)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panRoot)

--Create nodeRoot
local nodeRoot=cc.Node:create()
nodeRoot:setName("nodeRoot")
nodeRoot:setTag(605)
nodeRoot:setCascadeColorEnabled(true)
nodeRoot:setCascadeOpacityEnabled(true)
nodeRoot:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nodeRoot)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(640.0000)
layout:setRightMargin(640.0000)
layout:setTopMargin(360.0000)
layout:setBottomMargin(360.0000)
Layer:addChild(nodeRoot)

--Create img1
local img1 = ccui.ImageView:create()
img1:ignoreContentAdaptWithSize(false)
img1:loadTexture("GameScene/bt-dinglai1.png",0)
img1:setLayoutComponentEnabled(true)
img1:setName("img1")
img1:setTag(604)
img1:setCascadeColorEnabled(true)
img1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img1)
layout:setSize({width = 294.0000, height = 280.0000})
layout:setLeftMargin(-147.0000)
layout:setRightMargin(-147.0000)
layout:setTopMargin(-140.0000)
layout:setBottomMargin(-140.0000)
nodeRoot:addChild(img1)

--Create img2
local img2 = ccui.ImageView:create()
img2:ignoreContentAdaptWithSize(false)
img2:loadTexture("GameScene/bt-dinglai2.png",0)
img2:setLayoutComponentEnabled(true)
img2:setName("img2")
img2:setTag(603)
img2:setCascadeColorEnabled(true)
img2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img2)
layout:setSize({width = 378.0000, height = 145.0000})
layout:setLeftMargin(-189.0000)
layout:setRightMargin(-189.0000)
layout:setTopMargin(-72.5000)
layout:setBottomMargin(-72.5000)
nodeRoot:addChild(img2)

--Create imgCard
local imgCard = ccui.ImageView:create()
imgCard:ignoreContentAdaptWithSize(false)
imgCard:loadTexture("GameScene/vertical/mingmah_39.png",0)
imgCard:setLayoutComponentEnabled(true)
imgCard:setName("imgCard")
imgCard:setTag(602)
imgCard:setCascadeColorEnabled(true)
imgCard:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard)
layout:setSize({width = 89.0000, height = 135.0000})
layout:setLeftMargin(-44.5000)
layout:setRightMargin(-44.5000)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(-67.5000)
nodeRoot:addChild(imgCard)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

