--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorType(1)
panRoot:setBackGroundColor({r = 0, g = 0, b = 0})
panRoot:setBackGroundColorOpacity(140)
panRoot:setTouchEnabled(true);
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(248)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panRoot)

--Create imgBg
local imgBg = ccui.ImageView:create()
imgBg:ignoreContentAdaptWithSize(false)
imgBg:loadTexture("public/bf-di.png",0)
imgBg:setScale9Enabled(true)
imgBg:setCapInsets({x = 491, y = 10, width = 32, height = 593})
imgBg:setLayoutComponentEnabled(true)
imgBg:setName("imgBg")
imgBg:setTag(223)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(641.3480, 335.7371)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentX(0.5011)
layout:setPositionPercentY(0.4663)
layout:setPercentWidth(0.7813)
layout:setPercentHeight(0.8250)
layout:setSize({width = 1000.0000, height = 594.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(141.3480)
layout:setRightMargin(138.6520)
layout:setTopMargin(87.2629)
layout:setBottomMargin(38.7371)
Layer:addChild(imgBg)

--Create imgContentBg
local imgContentBg = ccui.ImageView:create()
imgContentBg:ignoreContentAdaptWithSize(false)
imgContentBg:loadTexture("public/bf-tongyong3.png",0)
imgContentBg:setScale9Enabled(true)
imgContentBg:setCapInsets({x = 23, y = 23, width = 114, height = 114})
imgContentBg:setLayoutComponentEnabled(true)
imgContentBg:setName("imgContentBg")
imgContentBg:setTag(224)
imgContentBg:setCascadeColorEnabled(true)
imgContentBg:setCascadeOpacityEnabled(true)
imgContentBg:setPosition(500.1947, 299.2579)
layout = ccui.LayoutComponent:bindLayoutComponent(imgContentBg)
layout:setPositionPercentX(0.5002)
layout:setPositionPercentY(0.5038)
layout:setPercentWidth(0.9380)
layout:setPercentHeight(0.9327)
layout:setSize({width = 938.0000, height = 554.0000})
layout:setLeftMargin(31.1947)
layout:setRightMargin(30.8053)
layout:setTopMargin(17.7421)
layout:setBottomMargin(22.2579)
imgBg:addChild(imgContentBg)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("public/bf-di2.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 595, y = 14, width = 45, height = 4})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(244)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(500.1125, 578.6417)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.9741)
layout:setPercentWidth(1.0590)
layout:setPercentHeight(0.0623)
layout:setSize({width = 1059.0000, height = 37.0000})
layout:setLeftMargin(-29.3875)
layout:setRightMargin(-29.6125)
layout:setTopMargin(-3.1417)
layout:setBottomMargin(560.1417)
imgBg:addChild(Image_1)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("public/bf-di3.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(245)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(529.5823, 16.3991)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.4432)
layout:setPercentWidth(0.3362)
layout:setPercentHeight(1.2973)
layout:setSize({width = 356.0000, height = 48.0000})
layout:setLeftMargin(351.5823)
layout:setRightMargin(351.4177)
layout:setTopMargin(-3.3991)
layout:setBottomMargin(-7.6009)
Image_1:addChild(Image_3)

--Create cbRoomRules
local cbRoomRules = ccui.CheckBox:create()
cbRoomRules:ignoreContentAdaptWithSize(false)
cbRoomRules:loadTextureBackGround("GameScene/bt-fangjianguize2.png",0)
cbRoomRules:loadTextureBackGroundSelected("GameScene/bt-fangjianguize2.png",0)
cbRoomRules:loadTextureBackGroundDisabled("GameScene/bt-fangjianguize2.png",0)
cbRoomRules:loadTextureFrontCross("GameScene/bt-fangjianguize1.png",0)
cbRoomRules:loadTextureFrontCrossDisabled("GameScene/bt-fangjianguize2.png",0)
cbRoomRules:setSelected(true)
cbRoomRules:setLayoutComponentEnabled(true)
cbRoomRules:setName("cbRoomRules")
cbRoomRules:setTag(328)
cbRoomRules:setCascadeColorEnabled(true)
cbRoomRules:setCascadeOpacityEnabled(true)
cbRoomRules:setPosition(168.5665, 475.6871)
layout = ccui.LayoutComponent:bindLayoutComponent(cbRoomRules)
layout:setPositionPercentX(0.1686)
layout:setPositionPercentY(0.8008)
layout:setPercentWidth(0.1780)
layout:setPercentHeight(0.1010)
layout:setSize({width = 178.0000, height = 60.0000})
layout:setLeftMargin(79.5665)
layout:setRightMargin(742.4335)
layout:setTopMargin(88.3129)
layout:setBottomMargin(445.6871)
imgBg:addChild(cbRoomRules)

--Create cbCardRules
local cbCardRules = ccui.CheckBox:create()
cbCardRules:ignoreContentAdaptWithSize(false)
cbCardRules:loadTextureBackGround("GameScene/bt-paixingguize2.png",0)
cbCardRules:loadTextureBackGroundSelected("GameScene/bt-paixingguize2.png",0)
cbCardRules:loadTextureBackGroundDisabled("GameScene/bt-paixingguize2.png",0)
cbCardRules:loadTextureFrontCross("GameScene/bt-paixingguize1.png",0)
cbCardRules:loadTextureFrontCrossDisabled("GameScene/bt-paixingguize2.png",0)
cbCardRules:setSelected(true)
cbCardRules:setLayoutComponentEnabled(true)
cbCardRules:setName("cbCardRules")
cbCardRules:setTag(329)
cbCardRules:setCascadeColorEnabled(true)
cbCardRules:setCascadeOpacityEnabled(true)
cbCardRules:setPosition(357.1293, 477.1159)
layout = ccui.LayoutComponent:bindLayoutComponent(cbCardRules)
layout:setPositionPercentX(0.3571)
layout:setPositionPercentY(0.8032)
layout:setPercentWidth(0.1780)
layout:setPercentHeight(0.1010)
layout:setSize({width = 178.0000, height = 60.0000})
layout:setLeftMargin(268.1293)
layout:setRightMargin(553.8707)
layout:setTopMargin(86.8841)
layout:setBottomMargin(447.1159)
imgBg:addChild(cbCardRules)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("public/bt-guangbi.png",0)
btnClose:loadTexturePressed("public/bt-guangbi.png",0)
btnClose:loadTextureDisabled("public/bt-guangbi.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor({r = 65, g = 65, b = 70})
btnClose:setScale9Enabled(true)
btnClose:setCapInsets({x = 15, y = 11, width = 78, height = 88})
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(246)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(1009.4420, 582.6909)
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentX(1.0094)
layout:setPositionPercentY(0.9810)
layout:setPercentWidth(0.1080)
layout:setPercentHeight(0.1852)
layout:setSize({width = 108.0000, height = 110.0000})
layout:setLeftMargin(955.4419)
layout:setRightMargin(-63.4419)
layout:setTopMargin(-43.6909)
layout:setBottomMargin(527.6909)
imgBg:addChild(btnClose)

--Create imgCardRules
local imgCardRules = ccui.ImageView:create()
imgCardRules:ignoreContentAdaptWithSize(false)
imgCardRules:loadTexture("public/bf-tongyong4.png",0)
imgCardRules:setScale9Enabled(true)
imgCardRules:setCapInsets({x = 110, y = 25, width = 116, height = 28})
imgCardRules:setLayoutComponentEnabled(true)
imgCardRules:setName("imgCardRules")
imgCardRules:setTag(251)
imgCardRules:setCascadeColorEnabled(true)
imgCardRules:setCascadeOpacityEnabled(true)
imgCardRules:setAnchorPoint(0.0000, 1.0000)
imgCardRules:setPosition(58.3442, 448.3888)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCardRules)
layout:setPositionPercentX(0.0583)
layout:setPositionPercentY(0.7549)
layout:setPercentWidth(0.8800)
layout:setPercentHeight(0.6734)
layout:setSize({width = 880.0000, height = 400.0000})
layout:setLeftMargin(58.3442)
layout:setRightMargin(61.6558)
layout:setTopMargin(145.6112)
layout:setBottomMargin(48.3888)
imgBg:addChild(imgCardRules)

--Create svContent
local svContent = ccui.ScrollView:create()
svContent:setBounceEnabled(true)
svContent:setInnerContainerSize({width = 880, height = 2480})
svContent:ignoreContentAdaptWithSize(false)
svContent:setClippingEnabled(true)
svContent:setBackGroundColorOpacity(102)
svContent:setLayoutComponentEnabled(true)
svContent:setName("svContent")
svContent:setTag(225)
svContent:setCascadeColorEnabled(true)
svContent:setCascadeOpacityEnabled(true)
svContent:setAnchorPoint(0.0000, 1.0000)
svContent:setPosition(3.9997, 387.5139)
layout = ccui.LayoutComponent:bindLayoutComponent(svContent)
layout:setPositionPercentX(0.0045)
layout:setPositionPercentY(0.9688)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9500)
layout:setSize({width = 880.0000, height = 380.0000})
layout:setLeftMargin(3.9997)
layout:setRightMargin(-3.9997)
layout:setTopMargin(12.4861)
layout:setBottomMargin(7.5139)
imgCardRules:addChild(svContent)

--Create lblContent
local lblContent = ccui.Text:create()
lblContent:ignoreContentAdaptWithSize(false)
lblContent:setFontName("font/DFYuanW7-GB2312.ttf")
lblContent:setFontSize(20)
lblContent:setString([[                            黄冈麻将规则
麻将介绍
黄冈麻将游戏使用筒、条、万三种花色，每种花色分别按数字排列从1－9（如：一万、二万……九万），东、南、西、北风、中、发、白，每种完全相同的牌各四张，一共是136张牌。
赖子
	 "赖子"是在四个选手闲家抓完13张牌庄家抓完第14张牌后翻取的第一张牌加一就是"赖子"（比如 A、翻出五万，六万就是"赖子"，翻出九万，一万就是"赖子"，B、按照"东、南、西、北、红中、发财、白板"的顺序，如果翻出"北"，跳过"红中"，"发财"是"赖子"，翻出"白板"，"东"是"赖子"）。
赖子可以当作其他张牌（万能牌）来胡（属于软胡，×1），也可以用本身花数胡（硬胡，×2）。 

出牌
	凡是抓进或吃、碰、开杠、补牌后，不胡牌便要打出一张牌。在游戏中不能出（红中、赖子、赖子皮）。
吃牌
	只能吃上家打出的牌，与自己手中的牌可以组成一副顺子，便可以报吃，把组成的顺子摆亮在立牌前。允许吃进（或碰或扛）打出的牌。
碰牌
	有人打出的牌与自己手中的对子相同，便可报碰，组成一副刻子并摆亮在立牌前。"碰"比"吃"优先。
杠牌
	只要有符合条件而且轮到自己出牌的时候即可随时杠。
	如果这张牌是红中，赖子皮，赖子，可以直接杠这张牌（将这张牌翻出但是不打出），然后再到整个牌墙的最后开始摸牌。
如果这张牌不是红中，赖子皮，赖子，而且起牌者已经碰了三张同样的牌了，则可以蓄杠，即将这张牌与已经碰的三张牌放到一起。在此期间，可以发生抢杠，然后再到整个牌墙的最后开始摸牌。
如果这张牌不是红中，赖子皮，赖子，而且起牌者已经有三张同样的牌了(但是不是碰的)，则可以暗杠，即将四张牌背面朝上，然后再到整个牌墙的最后开始摸牌。
胡牌要求
	1. 胡牌的基本牌型 
(1)11、123、123、123、123
 (2)11、123、123、123、111(1111，下同) 
(3)11、123、123、111、111 
(4)11、123、111、111、111 
(5)11、111、111、 111、111。
    注：除风一色、将一色、碰碰胡、清一色以外，一对（11）必须是一对将，即筒、条、万的二、五、八。
    2. 黄冈麻将没有7对子和门前清。
    3. 当有两个"赖子"时不能胡"小胡"（听牌时有一个"赖子"，又自摸一个"赖子"，必须打出一个），"赖子"可开杠（× 2），也可打出（× 2）。
    4. 风一色、将一色为乱风乱将，只要手上全是风牌或将牌就能胡牌。（在听牌时，任意风或将都能当炮使用。）
    5. 如果玩家漏掉了炮胡，可以继续胡其他玩家放的炮，无须等待自己摸牌后。
此外，在武汉麻将中，胡牌时手牌不能有红中与赖子皮，也不能有四张同样的牌，必须暗杠。在胡牌之前至少有一次开口，如果是在胡牌的那一张牌才开口则不算。
胡牌类型
小胡（即屁胡，基础分1），必须用二、五、八的对子做将牌。
大胡（基础分10，可累计）：
碰碰胡：即所有牌型为AAA，而且至少有一次开口，对牌可以不是将。
 
风一色：所有的牌都是东南西北白，这种情况并不需要碰或者对，但是仍然需要至少碰一次   
 
将一色：所有的牌都是2、5、8的条、筒、万，这种情况下并不需要碰或者对，但是仍然需要至少碰一次
 
清一色：所有的牌都是同一种花色，例如条、筒、万，牌型需要是小胡的牌型或者碰碰胡的牌型，对牌可以不是将。
 
 
 
海底捞：即起最后一张牌的时候(除了整个牌墙的最后10张牌以外的最后一张)胡牌，但是此牌不能用来杠、也不能打出，只能自摸胡

杠上开花：即在杠牌以后(包括明杠、暗杠、中发赖子杠)起了牌墙的最后一张以后胡牌。
 
全求人：所有的牌都是吃、碰、杠牌(不含暗杠)，如果是小胡牌型则最后一对牌必须是2、5、8的条、筒、万。
 
抢杠：X已经碰了一张牌，又起到了一张同样的牌可以杠(明杠)的时候，如果其他玩家可以胡这张牌，则称其为抢杠。

硬胡，是指胡牌后没有赖子、赖子被杠、用本身花数胡的情况。
软胡，如果有赖子并且充当万能牌使用的情况

一炮单响
只能有一个胡牌者，以庄家逆时针为序。

包胡
承包者承担所有输点，以下情况承包：
1） A放冲给B作全求人，A包胡。
2） B胡清一色，B的第三次开口对象是A，A承包。
3） B抢杠胡，被抢的A承包。
算番
	小胡又称屁胡，基数为1，大胡基数是10。
大胡可以叠加，例如同时胡风一色与全求人，即可将基数变为10+10=20，同时胡全求人，风一色与碰碰胡，即为30。
红中发财杠1番，赖子杠2番，明杠2番，暗杠2番，吃1番，碰1番，自摸1番，放冲1番，庄家1番，硬胡1番。其中硬胡表示没有赖子或者没有使用赖子混牌，而是用赖子的本来点数胡。
如果是蓄杠被抢杠了，蓄杠因为是明杠，仍然算两番。输家输去的点数=基数x2^(番数)（自己与赢家番数之和）。
对于风一色、将一色、清一色与碰碰胡，如果是自摸，此时番数比较特殊，为其他番数算完以后得到的2的次方的结果再乘以1.5。
海底捞与杠上开花的自摸不算番数。对于大胡来说，庄家不算番。
封顶
	每个输家输点最高不超过80，超过80则为80。
但是有下列特殊情况则需要调整封顶(在下面开口的定义不仅包括吃、碰、明杠，也包括红中发财赖子杠)：
如果输家的最低点数不超过80，则每家输的点数最多是80，如果低于80按照实际点数算。
如果每家输的点数都超过80，而且都开口了，则每家都付100(金顶)。
如果每家输的点数都超过80，而且有一个或者两个输家没有开口，则没有开口的输家要加付给赢家20，即120(哈顶)。
如果每家输的点数都超过80，而且三家都没有开口，则所有人都付160(三阳开泰)。
如果胡的是风一色，则每家不算实际番数，均按照每家输点超过80来算，即只与各输家的开口有关]])
lblContent:setLayoutComponentEnabled(true)
lblContent:setName("lblContent")
lblContent:setTag(271)
lblContent:setCascadeColorEnabled(true)
lblContent:setCascadeOpacityEnabled(true)
lblContent:setAnchorPoint(0.0000, 1.0000)
lblContent:setPosition(12.9948, 2480.0000)
lblContent:setTextColor({r = 90, g = 36, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(lblContent)
layout:setPositionPercentX(0.0148)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(0.9659)
layout:setPercentHeight(1.0000)
layout:setSize({width = 850.0000, height = 2480.0000})
layout:setLeftMargin(12.9948)
layout:setRightMargin(17.0052)
svContent:addChild(lblContent)

--Create txtTitle
local txtTitle = ccui.Text:create()
txtTitle:ignoreContentAdaptWithSize(true)
txtTitle:setTextAreaSize({width = 0, height = 0})
txtTitle:setFontName("font/DFYuanW7-GB2312.ttf")
txtTitle:setFontSize(34)
txtTitle:setString([[房间规则]])
txtTitle:setLayoutComponentEnabled(true)
txtTitle:setName("txtTitle")
txtTitle:setTag(247)
txtTitle:setCascadeColorEnabled(true)
txtTitle:setCascadeOpacityEnabled(true)
txtTitle:setPosition(500.1946, 576.4886)
layout = ccui.LayoutComponent:bindLayoutComponent(txtTitle)
layout:setPositionPercentX(0.5002)
layout:setPositionPercentY(0.9705)
layout:setPercentWidth(0.1360)
layout:setPercentHeight(0.0657)
layout:setSize({width = 136.0000, height = 39.0000})
layout:setLeftMargin(432.1946)
layout:setRightMargin(431.8054)
layout:setTopMargin(-1.9886)
layout:setBottomMargin(556.9886)
imgBg:addChild(txtTitle)

--Create imgRoomRules
local imgRoomRules = ccui.ImageView:create()
imgRoomRules:ignoreContentAdaptWithSize(false)
imgRoomRules:loadTexture("public/bf-tongyong4.png",0)
imgRoomRules:setScale9Enabled(true)
imgRoomRules:setCapInsets({x = 110, y = 25, width = 116, height = 28})
imgRoomRules:setLayoutComponentEnabled(true)
imgRoomRules:setName("imgRoomRules")
imgRoomRules:setTag(252)
imgRoomRules:setCascadeColorEnabled(true)
imgRoomRules:setCascadeOpacityEnabled(true)
imgRoomRules:setAnchorPoint(0.0000, 1.0000)
imgRoomRules:setPosition(58.3400, 448.3900)
layout = ccui.LayoutComponent:bindLayoutComponent(imgRoomRules)
layout:setPositionPercentX(0.0583)
layout:setPositionPercentY(0.7549)
layout:setPercentWidth(0.8800)
layout:setPercentHeight(0.6734)
layout:setSize({width = 880.0000, height = 400.0000})
layout:setLeftMargin(58.3400)
layout:setRightMargin(61.6600)
layout:setTopMargin(145.6100)
layout:setBottomMargin(48.3900)
imgBg:addChild(imgRoomRules)

--Create Text_1_2
local Text_1_2 = ccui.Text:create()
Text_1_2:ignoreContentAdaptWithSize(true)
Text_1_2:setTextAreaSize({width = 0, height = 0})
Text_1_2:setFontName("font/DFYuanW7-GB2312.ttf")
Text_1_2:setFontSize(30)
Text_1_2:setString([[玩法选项：]])
Text_1_2:setLayoutComponentEnabled(true)
Text_1_2:setName("Text_1_2")
Text_1_2:setTag(322)
Text_1_2:setCascadeColorEnabled(true)
Text_1_2:setCascadeOpacityEnabled(true)
Text_1_2:setAnchorPoint(0.0000, 0.5000)
Text_1_2:setPosition(66.6683, 188.5565)
Text_1_2:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_2)
layout:setPositionPercentX(0.0758)
layout:setPositionPercentY(0.4714)
layout:setPercentWidth(0.1511)
layout:setPercentHeight(0.0850)
layout:setSize({width = 133.0000, height = 34.0000})
layout:setLeftMargin(66.6683)
layout:setRightMargin(680.3317)
layout:setTopMargin(194.4435)
layout:setBottomMargin(171.5565)
imgRoomRules:addChild(Text_1_2)

--Create Text_1_1
local Text_1_1 = ccui.Text:create()
Text_1_1:ignoreContentAdaptWithSize(true)
Text_1_1:setTextAreaSize({width = 0, height = 0})
Text_1_1:setFontName("font/DFYuanW7-GB2312.ttf")
Text_1_1:setFontSize(28)
Text_1_1:setString([[起胡番数：]])
Text_1_1:setLayoutComponentEnabled(true)
Text_1_1:setName("Text_1_1")
Text_1_1:setTag(323)
Text_1_1:setCascadeColorEnabled(true)
Text_1_1:setCascadeOpacityEnabled(true)
Text_1_1:setAnchorPoint(0.0000, 0.5000)
Text_1_1:setPosition(66.6683, 256.7589)
Text_1_1:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_1)
layout:setPositionPercentX(0.0758)
layout:setPositionPercentY(0.6419)
layout:setPercentWidth(0.1409)
layout:setPercentHeight(0.0800)
layout:setSize({width = 124.0000, height = 32.0000})
layout:setLeftMargin(66.6683)
layout:setRightMargin(689.3317)
layout:setTopMargin(127.2411)
layout:setBottomMargin(240.7589)
imgRoomRules:addChild(Text_1_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("font/DFYuanW7-GB2312.ttf")
Text_1:setFontSize(30)
Text_1:setString([[局数：]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(324)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 0.5000)
Text_1:setPosition(122.6683, 324.5507)
Text_1:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.1394)
layout:setPositionPercentY(0.8114)
layout:setPercentWidth(0.0830)
layout:setPercentHeight(0.0850)
layout:setSize({width = 73.0000, height = 34.0000})
layout:setLeftMargin(122.6683)
layout:setRightMargin(684.3317)
layout:setTopMargin(58.4493)
layout:setBottomMargin(307.5507)
imgRoomRules:addChild(Text_1)

--Create txtOptions
local txtOptions = ccui.Text:create()
txtOptions:ignoreContentAdaptWithSize(true)
txtOptions:setTextAreaSize({width = 0, height = 0})
txtOptions:setFontName("font/DFYuanW7-GB2312.ttf")
txtOptions:setFontSize(30)
txtOptions:setString([[玩法选项：]])
txtOptions:setLayoutComponentEnabled(true)
txtOptions:setName("txtOptions")
txtOptions:setTag(325)
txtOptions:setCascadeColorEnabled(true)
txtOptions:setCascadeOpacityEnabled(true)
txtOptions:setAnchorPoint(0.0000, 0.5000)
txtOptions:setPosition(226.3358, 191.4582)
txtOptions:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(txtOptions)
layout:setPositionPercentX(0.2572)
layout:setPositionPercentY(0.4786)
layout:setPercentWidth(0.1511)
layout:setPercentHeight(0.0850)
layout:setSize({width = 133.0000, height = 34.0000})
layout:setLeftMargin(226.3358)
layout:setRightMargin(520.6642)
layout:setTopMargin(191.5418)
layout:setBottomMargin(174.4582)
imgRoomRules:addChild(txtOptions)

--Create txtFans
local txtFans = ccui.Text:create()
txtFans:ignoreContentAdaptWithSize(true)
txtFans:setTextAreaSize({width = 0, height = 0})
txtFans:setFontName("font/DFYuanW7-GB2312.ttf")
txtFans:setFontSize(30)
txtFans:setString([[起胡番数：]])
txtFans:setLayoutComponentEnabled(true)
txtFans:setName("txtFans")
txtFans:setTag(326)
txtFans:setCascadeColorEnabled(true)
txtFans:setCascadeOpacityEnabled(true)
txtFans:setAnchorPoint(0.0000, 0.5000)
txtFans:setPosition(226.3358, 259.6609)
txtFans:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(txtFans)
layout:setPositionPercentX(0.2572)
layout:setPositionPercentY(0.6492)
layout:setPercentWidth(0.1511)
layout:setPercentHeight(0.0850)
layout:setSize({width = 133.0000, height = 34.0000})
layout:setLeftMargin(226.3358)
layout:setRightMargin(520.6642)
layout:setTopMargin(123.3391)
layout:setBottomMargin(242.6609)
imgRoomRules:addChild(txtFans)

--Create txtRolls
local txtRolls = ccui.Text:create()
txtRolls:ignoreContentAdaptWithSize(true)
txtRolls:setTextAreaSize({width = 0, height = 0})
txtRolls:setFontName("font/DFYuanW7-GB2312.ttf")
txtRolls:setFontSize(30)
txtRolls:setString([[16局]])
txtRolls:setLayoutComponentEnabled(true)
txtRolls:setName("txtRolls")
txtRolls:setTag(327)
txtRolls:setCascadeColorEnabled(true)
txtRolls:setCascadeOpacityEnabled(true)
txtRolls:setAnchorPoint(0.0000, 0.5000)
txtRolls:setPosition(226.3358, 326.1619)
txtRolls:setTextColor({r = 59, g = 21, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(txtRolls)
layout:setPositionPercentX(0.2572)
layout:setPositionPercentY(0.8154)
layout:setPercentWidth(0.0705)
layout:setPercentHeight(0.0850)
layout:setSize({width = 62.0000, height = 34.0000})
layout:setLeftMargin(226.3358)
layout:setRightMargin(591.6642)
layout:setTopMargin(56.8381)
layout:setBottomMargin(309.1619)
imgRoomRules:addChild(txtRolls)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

