--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorOpacity(102)
panRoot:setTouchEnabled(true);
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(69)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panRoot)

--Create imgBg
local imgBg = ccui.ImageView:create()
imgBg:ignoreContentAdaptWithSize(false)
imgBg:loadTexture("GameScene/bg-zezhao.png",0)
imgBg:setScale9Enabled(true)
imgBg:setCapInsets({x = 13, y = 274, width = 1252, height = 172})
imgBg:setLayoutComponentEnabled(true)
imgBg:setName("imgBg")
imgBg:setTag(70)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(635.6218, 362.8573)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentX(0.4966)
layout:setPositionPercentY(0.5040)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(-4.3782)
layout:setRightMargin(4.3782)
layout:setTopMargin(-2.8573)
layout:setBottomMargin(2.8573)
Layer:addChild(imgBg)

--Create panMenu
local panMenu = ccui.Layout:create()
panMenu:ignoreContentAdaptWithSize(false)
panMenu:setClippingEnabled(false)
panMenu:setBackGroundColorOpacity(102)
panMenu:setLayoutComponentEnabled(true)
panMenu:setName("panMenu")
panMenu:setTag(337)
panMenu:setCascadeColorEnabled(true)
panMenu:setCascadeOpacityEnabled(true)
panMenu:setAnchorPoint(1.0000, 0.0000)
panMenu:setPosition(1280.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panMenu)
layout:setPositionPercentX(1.0000)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(1.0000)
layout:setSize({width = 200.0000, height = 720.0000})
layout:setLeftMargin(1080.0000)
Layer:addChild(panMenu)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("GameScene/bt-caidan.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(336)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(119.0306, 636.0742)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5952)
layout:setPositionPercentY(0.8834)
layout:setPercentWidth(0.6500)
layout:setPercentHeight(0.1806)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(54.0306)
layout:setRightMargin(15.9694)
layout:setTopMargin(18.9258)
layout:setBottomMargin(571.0742)
panMenu:addChild(Image_1)

--Create btnRecord
local btnRecord = ccui.Button:create()
btnRecord:ignoreContentAdaptWithSize(false)
btnRecord:loadTextureNormal("GameScene/bt-jilu.png",0)
btnRecord:loadTexturePressed("GameScene/bt-jilu.png",0)
btnRecord:loadTextureDisabled("Default/Button_Disable.png",0)
btnRecord:setTitleFontSize(14)
btnRecord:setTitleColor({r = 65, g = 65, b = 70})
btnRecord:setScale9Enabled(true)
btnRecord:setCapInsets({x = 15, y = 11, width = 100, height = 108})
btnRecord:setLayoutComponentEnabled(true)
btnRecord:setName("btnRecord")
btnRecord:setTag(339)
btnRecord:setCascadeColorEnabled(true)
btnRecord:setCascadeOpacityEnabled(true)
btnRecord:setPosition(119.0306, 338.0419)
layout = ccui.LayoutComponent:bindLayoutComponent(btnRecord)
layout:setPositionPercentX(0.5952)
layout:setPositionPercentY(0.4695)
layout:setPercentWidth(0.6500)
layout:setPercentHeight(0.1806)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(54.0306)
layout:setRightMargin(15.9694)
layout:setTopMargin(316.9581)
layout:setBottomMargin(273.0419)
panMenu:addChild(btnRecord)

--Create btnRules
local btnRules = ccui.Button:create()
btnRules:ignoreContentAdaptWithSize(false)
btnRules:loadTextureNormal("GameScene/bt-guize.png",0)
btnRules:loadTexturePressed("GameScene/bt-guize.png",0)
btnRules:loadTextureDisabled("GameScene/bt-guize.png",0)
btnRules:setTitleFontSize(14)
btnRules:setTitleColor({r = 65, g = 65, b = 70})
btnRules:setScale9Enabled(true)
btnRules:setCapInsets({x = 15, y = 11, width = 100, height = 108})
btnRules:setLayoutComponentEnabled(true)
btnRules:setName("btnRules")
btnRules:setTag(340)
btnRules:setCascadeColorEnabled(true)
btnRules:setCascadeOpacityEnabled(true)
btnRules:setPosition(119.0306, 487.0580)
layout = ccui.LayoutComponent:bindLayoutComponent(btnRules)
layout:setPositionPercentX(0.5952)
layout:setPositionPercentY(0.6765)
layout:setPercentWidth(0.6500)
layout:setPercentHeight(0.1806)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(54.0306)
layout:setRightMargin(15.9694)
layout:setTopMargin(167.9420)
layout:setBottomMargin(422.0580)
panMenu:addChild(btnRules)

--Create btnExit
local btnExit = ccui.Button:create()
btnExit:ignoreContentAdaptWithSize(false)
btnExit:loadTextureNormal("GameScene/bt-tuichu.png",0)
btnExit:loadTexturePressed("GameScene/bt-tuichu.png",0)
btnExit:loadTextureDisabled("GameScene/bt-tuichu.png",0)
btnExit:setTitleFontSize(14)
btnExit:setTitleColor({r = 65, g = 65, b = 70})
btnExit:setScale9Enabled(true)
btnExit:setCapInsets({x = 15, y = 11, width = 100, height = 108})
btnExit:setLayoutComponentEnabled(true)
btnExit:setName("btnExit")
btnExit:setTag(338)
btnExit:setCascadeColorEnabled(true)
btnExit:setCascadeOpacityEnabled(true)
btnExit:setPosition(117.8548, 190.0725)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExit)
layout:setPositionPercentX(0.5893)
layout:setPositionPercentY(0.2640)
layout:setPercentWidth(0.6500)
layout:setPercentHeight(0.1806)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(52.8548)
layout:setRightMargin(17.1452)
layout:setTopMargin(464.9275)
layout:setBottomMargin(125.0725)
panMenu:addChild(btnExit)

--Create btnDismiss
local btnDismiss = ccui.Button:create()
btnDismiss:ignoreContentAdaptWithSize(false)
btnDismiss:loadTextureNormal("GameScene/bt-jiesan.png",0)
btnDismiss:loadTexturePressed("GameScene/bt-jiesan.png",0)
btnDismiss:loadTextureDisabled("GameScene/bt-jiesan.png",0)
btnDismiss:setTitleFontSize(14)
btnDismiss:setTitleColor({r = 65, g = 65, b = 70})
btnDismiss:setScale9Enabled(true)
btnDismiss:setCapInsets({x = 15, y = 11, width = 100, height = 108})
btnDismiss:setLayoutComponentEnabled(true)
btnDismiss:setName("btnDismiss")
btnDismiss:setTag(73)
btnDismiss:setCascadeColorEnabled(true)
btnDismiss:setCascadeOpacityEnabled(true)
btnDismiss:setPosition(119.0308, 189.0257)
layout = ccui.LayoutComponent:bindLayoutComponent(btnDismiss)
layout:setPositionPercentX(0.5952)
layout:setPositionPercentY(0.2625)
layout:setPercentWidth(0.6500)
layout:setPercentHeight(0.1806)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(54.0308)
layout:setRightMargin(15.9692)
layout:setTopMargin(465.9743)
layout:setBottomMargin(124.0257)
panMenu:addChild(btnDismiss)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

