--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btnGuo
local btnGuo = ccui.Button:create()
btnGuo:ignoreContentAdaptWithSize(false)
btnGuo:loadTextureNormal("GameScene/bt-guo.png",0)
btnGuo:loadTexturePressed("GameScene/bt-guo.png",0)
btnGuo:loadTextureDisabled("Default/Button_Disable.png",0)
btnGuo:setTitleFontSize(14)
btnGuo:setTitleColor({r = 65, g = 65, b = 70})
btnGuo:setScale9Enabled(true)
btnGuo:setCapInsets({x = 15, y = 11, width = 76, height = 84})
btnGuo:setLayoutComponentEnabled(true)
btnGuo:setName("btnGuo")
btnGuo:setTag(86)
btnGuo:setCascadeColorEnabled(true)
btnGuo:setCascadeOpacityEnabled(true)
btnGuo:setPosition(-49.9358, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnGuo)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-102.9358)
layout:setRightMargin(-3.0642)
layout:setTopMargin(-119.5417)
layout:setBottomMargin(13.5417)
Node:addChild(btnGuo)

--Create btnPeng
local btnPeng = ccui.Button:create()
btnPeng:ignoreContentAdaptWithSize(false)
btnPeng:loadTextureNormal("GameScene/bt-peng.png",0)
btnPeng:loadTexturePressed("GameScene/bt-peng.png",0)
btnPeng:loadTextureDisabled("Default/Button_Disable.png",0)
btnPeng:setTitleFontSize(14)
btnPeng:setTitleColor({r = 65, g = 65, b = 70})
btnPeng:setScale9Enabled(true)
btnPeng:setCapInsets({x = 15, y = 11, width = 76, height = 84})
btnPeng:setLayoutComponentEnabled(true)
btnPeng:setName("btnPeng")
btnPeng:setTag(85)
btnPeng:setCascadeColorEnabled(true)
btnPeng:setCascadeOpacityEnabled(true)
btnPeng:setPosition(-201.7922, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPeng)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-254.7922)
layout:setRightMargin(148.7922)
layout:setTopMargin(-119.5417)
layout:setBottomMargin(13.5417)
Node:addChild(btnPeng)

--Create btnChi
local btnChi = ccui.Button:create()
btnChi:ignoreContentAdaptWithSize(false)
btnChi:loadTextureNormal("GameScene/bt-chi.png",0)
btnChi:loadTexturePressed("GameScene/bt-chi.png",0)
btnChi:loadTextureDisabled("Default/Button_Disable.png",0)
btnChi:setTitleFontSize(14)
btnChi:setTitleColor({r = 65, g = 65, b = 70})
btnChi:setScale9Enabled(true)
btnChi:setCapInsets({x = 15, y = 11, width = 76, height = 84})
btnChi:setLayoutComponentEnabled(true)
btnChi:setName("btnChi")
btnChi:setTag(87)
btnChi:setCascadeColorEnabled(true)
btnChi:setCascadeOpacityEnabled(true)
btnChi:setPosition(-357.0481, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnChi)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-410.0481)
layout:setRightMargin(304.0481)
layout:setTopMargin(-119.5417)
layout:setBottomMargin(13.5417)
Node:addChild(btnChi)

--Create btnGang
local btnGang = ccui.Button:create()
btnGang:ignoreContentAdaptWithSize(false)
btnGang:loadTextureNormal("GameScene/bt-gang.png",0)
btnGang:loadTexturePressed("GameScene/bt-gang.png",0)
btnGang:loadTextureDisabled("Default/Button_Disable.png",0)
btnGang:setTitleFontSize(14)
btnGang:setTitleColor({r = 65, g = 65, b = 70})
btnGang:setScale9Enabled(true)
btnGang:setCapInsets({x = 15, y = 11, width = 76, height = 84})
btnGang:setLayoutComponentEnabled(true)
btnGang:setName("btnGang")
btnGang:setTag(88)
btnGang:setCascadeColorEnabled(true)
btnGang:setCascadeOpacityEnabled(true)
btnGang:setPosition(-664.1604, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnGang)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-717.1604)
layout:setRightMargin(611.1604)
layout:setTopMargin(-119.5417)
layout:setBottomMargin(13.5417)
Node:addChild(btnGang)

--Create btnHu
local btnHu = ccui.Button:create()
btnHu:ignoreContentAdaptWithSize(false)
btnHu:loadTextureNormal("GameScene/bt-hu.png",0)
btnHu:loadTexturePressed("GameScene/bt-hu.png",0)
btnHu:loadTextureDisabled("Default/Button_Disable.png",0)
btnHu:setTitleFontSize(14)
btnHu:setTitleColor({r = 65, g = 65, b = 70})
btnHu:setScale9Enabled(true)
btnHu:setCapInsets({x = 15, y = 11, width = 76, height = 84})
btnHu:setLayoutComponentEnabled(true)
btnHu:setName("btnHu")
btnHu:setTag(89)
btnHu:setCascadeColorEnabled(true)
btnHu:setCascadeOpacityEnabled(true)
btnHu:setPosition(-510.6042, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnHu)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-563.6042)
layout:setRightMargin(457.6042)
layout:setTopMargin(-119.5417)
layout:setBottomMargin(13.5417)
Node:addChild(btnHu)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

