--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorOpacity(102)
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(62)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panRoot)

--Create panNewPacket
local panNewPacket = ccui.Layout:create()
panNewPacket:ignoreContentAdaptWithSize(false)
panNewPacket:setClippingEnabled(false)
panNewPacket:setBackGroundColorType(1)
panNewPacket:setBackGroundColor({r = 150, g = 200, b = 255})
panNewPacket:setBackGroundColorOpacity(102)
panNewPacket:setTouchEnabled(true);
panNewPacket:setLayoutComponentEnabled(true)
panNewPacket:setName("panNewPacket")
panNewPacket:setTag(63)
panNewPacket:setCascadeColorEnabled(true)
panNewPacket:setCascadeOpacityEnabled(true)
panNewPacket:setPosition(405.9601, 234.8421)
layout = ccui.LayoutComponent:bindLayoutComponent(panNewPacket)
layout:setPositionPercentX(0.3172)
layout:setPositionPercentY(0.3262)
layout:setPercentWidth(0.3906)
layout:setPercentHeight(0.4167)
layout:setSize({width = 500.0000, height = 300.0000})
layout:setLeftMargin(405.9601)
layout:setRightMargin(374.0399)
layout:setTopMargin(185.1579)
layout:setBottomMargin(234.8421)
Layer:addChild(panNewPacket)

--Create lblDesc
local lblDesc = ccui.Text:create()
lblDesc:ignoreContentAdaptWithSize(true)
lblDesc:setTextAreaSize({width = 0, height = 0})
lblDesc:setFontSize(20)
lblDesc:setString([[请下载最新安装包，点击确定开始下载。]])
lblDesc:setLayoutComponentEnabled(true)
lblDesc:setName("lblDesc")
lblDesc:setTag(66)
lblDesc:setCascadeColorEnabled(true)
lblDesc:setCascadeOpacityEnabled(true)
lblDesc:setAnchorPoint(0.0000, 1.0000)
lblDesc:setPosition(65.1522, 235.4026)
layout = ccui.LayoutComponent:bindLayoutComponent(lblDesc)
layout:setPositionPercentX(0.1303)
layout:setPositionPercentY(0.7847)
layout:setPercentWidth(0.7200)
layout:setPercentHeight(0.0667)
layout:setSize({width = 360.0000, height = 20.0000})
layout:setLeftMargin(65.1522)
layout:setRightMargin(74.8478)
layout:setTopMargin(64.5974)
layout:setBottomMargin(215.4026)
panNewPacket:addChild(lblDesc)

--Create btnOk
local btnOk = ccui.Button:create()
btnOk:ignoreContentAdaptWithSize(false)
btnOk:loadTextureNormal("Default/Button_Normal.png",0)
btnOk:loadTexturePressed("Default/Button_Press.png",0)
btnOk:loadTextureDisabled("Default/Button_Disable.png",0)
btnOk:setTitleFontName("font/DFYuanW7-GB2312.ttf")
btnOk:setTitleFontSize(14)
btnOk:setTitleText("确定")
btnOk:setTitleColor({r = 65, g = 65, b = 70})
btnOk:setScale9Enabled(true)
btnOk:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btnOk:setLayoutComponentEnabled(true)
btnOk:setName("btnOk")
btnOk:setTag(67)
btnOk:setCascadeColorEnabled(true)
btnOk:setCascadeOpacityEnabled(true)
btnOk:setPosition(153.4128, 37.7625)
layout = ccui.LayoutComponent:bindLayoutComponent(btnOk)
layout:setPositionPercentX(0.3068)
layout:setPositionPercentY(0.1259)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.1200)
layout:setSize({width = 100.0000, height = 36.0000})
layout:setLeftMargin(103.4128)
layout:setRightMargin(296.5872)
layout:setTopMargin(244.2375)
layout:setBottomMargin(19.7625)
panNewPacket:addChild(btnOk)

--Create btnCancel
local btnCancel = ccui.Button:create()
btnCancel:ignoreContentAdaptWithSize(false)
btnCancel:loadTextureNormal("Default/Button_Normal.png",0)
btnCancel:loadTexturePressed("Default/Button_Press.png",0)
btnCancel:loadTextureDisabled("Default/Button_Disable.png",0)
btnCancel:setTitleFontName("font/DFYuanW7-GB2312.ttf")
btnCancel:setTitleFontSize(14)
btnCancel:setTitleText("取消")
btnCancel:setTitleColor({r = 65, g = 65, b = 70})
btnCancel:setScale9Enabled(true)
btnCancel:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btnCancel:setLayoutComponentEnabled(true)
btnCancel:setName("btnCancel")
btnCancel:setTag(68)
btnCancel:setCascadeColorEnabled(true)
btnCancel:setCascadeOpacityEnabled(true)
btnCancel:setPosition(362.8588, 38.7444)
layout = ccui.LayoutComponent:bindLayoutComponent(btnCancel)
layout:setPositionPercentX(0.7257)
layout:setPositionPercentY(0.1291)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.1200)
layout:setSize({width = 100.0000, height = 36.0000})
layout:setLeftMargin(312.8588)
layout:setRightMargin(87.1412)
layout:setTopMargin(243.2556)
layout:setBottomMargin(20.7444)
panNewPacket:addChild(btnCancel)

--Create panMsg
local panMsg = ccui.Layout:create()
panMsg:ignoreContentAdaptWithSize(false)
panMsg:setClippingEnabled(false)
panMsg:setBackGroundColorType(1)
panMsg:setBackGroundColor({r = 150, g = 200, b = 255})
panMsg:setBackGroundColorOpacity(102)
panMsg:setTouchEnabled(true);
panMsg:setLayoutComponentEnabled(true)
panMsg:setName("panMsg")
panMsg:setTag(69)
panMsg:setCascadeColorEnabled(true)
panMsg:setCascadeOpacityEnabled(true)
panMsg:setPosition(404.1594, 234.2831)
layout = ccui.LayoutComponent:bindLayoutComponent(panMsg)
layout:setPositionPercentX(0.3157)
layout:setPositionPercentY(0.3254)
layout:setPercentWidth(0.3906)
layout:setPercentHeight(0.4167)
layout:setSize({width = 500.0000, height = 300.0000})
layout:setLeftMargin(404.1594)
layout:setRightMargin(375.8406)
layout:setTopMargin(185.7169)
layout:setBottomMargin(234.2831)
Layer:addChild(panMsg)

--Create lblDesc
local lblDesc = ccui.Text:create()
lblDesc:ignoreContentAdaptWithSize(true)
lblDesc:setTextAreaSize({width = 0, height = 0})
lblDesc:setFontSize(20)
lblDesc:setString([[错误错误错误]])
lblDesc:setLayoutComponentEnabled(true)
lblDesc:setName("lblDesc")
lblDesc:setTag(70)
lblDesc:setCascadeColorEnabled(true)
lblDesc:setCascadeOpacityEnabled(true)
lblDesc:setAnchorPoint(0.0000, 1.0000)
lblDesc:setPosition(65.1522, 235.4026)
layout = ccui.LayoutComponent:bindLayoutComponent(lblDesc)
layout:setPositionPercentX(0.1303)
layout:setPositionPercentY(0.7847)
layout:setPercentWidth(0.2400)
layout:setPercentHeight(0.0667)
layout:setSize({width = 120.0000, height = 20.0000})
layout:setLeftMargin(65.1522)
layout:setRightMargin(314.8478)
layout:setTopMargin(64.5974)
layout:setBottomMargin(215.4026)
panMsg:addChild(lblDesc)

--Create btnOk
local btnOk = ccui.Button:create()
btnOk:ignoreContentAdaptWithSize(false)
btnOk:loadTextureNormal("Default/Button_Normal.png",0)
btnOk:loadTexturePressed("Default/Button_Press.png",0)
btnOk:loadTextureDisabled("Default/Button_Disable.png",0)
btnOk:setTitleFontName("font/DFYuanW7-GB2312.ttf")
btnOk:setTitleFontSize(14)
btnOk:setTitleText("确定")
btnOk:setTitleColor({r = 65, g = 65, b = 70})
btnOk:setScale9Enabled(true)
btnOk:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btnOk:setLayoutComponentEnabled(true)
btnOk:setName("btnOk")
btnOk:setTag(71)
btnOk:setCascadeColorEnabled(true)
btnOk:setCascadeOpacityEnabled(true)
btnOk:setPosition(258.4464, 38.9426)
layout = ccui.LayoutComponent:bindLayoutComponent(btnOk)
layout:setPositionPercentX(0.5169)
layout:setPositionPercentY(0.1298)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.1200)
layout:setSize({width = 100.0000, height = 36.0000})
layout:setLeftMargin(208.4464)
layout:setRightMargin(191.5536)
layout:setTopMargin(243.0574)
layout:setBottomMargin(20.9426)
panMsg:addChild(btnOk)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

