--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create loginBg_1
local loginBg_1 = cc.Sprite:create("LaunchScene/bg-dengluditu.png")
loginBg_1:setName("loginBg_1")
loginBg_1:setTag(222)
loginBg_1:setCascadeColorEnabled(true)
loginBg_1:setCascadeOpacityEnabled(true)
loginBg_1:setPosition(640.0002, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(loginBg_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.3333)
layout:setSize({width = 1280.0000, height = 960.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(0.0002)
layout:setRightMargin(-0.0002)
layout:setTopMargin(-120.0000)
layout:setBottomMargin(-120.0000)
loginBg_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(loginBg_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("LaunchScene/bf_dengluditu.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(41)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(639.9995, 359.2836)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4990)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(-0.0005)
layout:setRightMargin(0.0005)
layout:setTopMargin(0.7164)
layout:setBottomMargin(-0.7164)
Layer:addChild(Image_1)

--Create Sprite_1
local Sprite_1 = cc.Sprite:create("LaunchScene/bg-huangganmajiang.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(31)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(690.0000, 425.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentX(0.5391)
layout:setPositionPercentY(0.5903)
layout:setPercentWidth(0.4117)
layout:setPercentHeight(0.7139)
layout:setSize({width = 527.0000, height = 514.0000})
layout:setLeftMargin(426.5000)
layout:setRightMargin(326.5000)
layout:setTopMargin(38.0000)
layout:setBottomMargin(168.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_1)

--Create imgPlayerID
local imgPlayerID = ccui.ImageView:create()
imgPlayerID:ignoreContentAdaptWithSize(false)
imgPlayerID:loadTexture("GameScene/bg-zhezhao.png",0)
imgPlayerID:setScale9Enabled(true)
imgPlayerID:setCapInsets({x = 35, y = 7, width = 38, height = 8})
imgPlayerID:setLayoutComponentEnabled(true)
imgPlayerID:setName("imgPlayerID")
imgPlayerID:setTag(217)
imgPlayerID:setCascadeColorEnabled(true)
imgPlayerID:setCascadeOpacityEnabled(true)
imgPlayerID:setPosition(1090.6930, 199.4666)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerID)
layout:setPositionPercentX(0.8521)
layout:setPositionPercentY(0.2770)
layout:setPercentWidth(0.1883)
layout:setPercentHeight(0.0694)
layout:setSize({width = 241.0000, height = 50.0000})
layout:setLeftMargin(970.1934)
layout:setRightMargin(68.8066)
layout:setTopMargin(495.5334)
layout:setBottomMargin(174.4666)
Layer:addChild(imgPlayerID)

--Create txtPlayerID
local txtPlayerID = ccui.TextField:create()
txtPlayerID:ignoreContentAdaptWithSize(false)
tolua.cast(txtPlayerID:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
txtPlayerID:setFontName("font/DFYuanW7-GB2312.ttf")
txtPlayerID:setFontSize(36)
txtPlayerID:setPlaceHolder("玩家ID")
txtPlayerID:setString([[]])
txtPlayerID:setMaxLength(10)
txtPlayerID:setLayoutComponentEnabled(true)
txtPlayerID:setName("txtPlayerID")
txtPlayerID:setTag(218)
txtPlayerID:setCascadeColorEnabled(true)
txtPlayerID:setCascadeOpacityEnabled(true)
txtPlayerID:setAnchorPoint(0.5000, 0.4756)
txtPlayerID:setPosition(120.6003, 24.3299)
txtPlayerID:setColor({r = 255, g = 253, b = 253})
layout = ccui.LayoutComponent:bindLayoutComponent(txtPlayerID)
layout:setPositionPercentX(0.5004)
layout:setPositionPercentY(0.4866)
layout:setPercentWidth(0.9585)
layout:setPercentHeight(0.7200)
layout:setSize({width = 231.0000, height = 36.0000})
layout:setLeftMargin(5.1003)
layout:setRightMargin(4.8997)
layout:setTopMargin(6.7917)
layout:setBottomMargin(7.2083)
imgPlayerID:addChild(txtPlayerID)

--Create btnLogin
local btnLogin = ccui.Button:create()
btnLogin:ignoreContentAdaptWithSize(false)
btnLogin:loadTextureNormal("LaunchScene/bt-denglu.png",0)
btnLogin:loadTexturePressed("LaunchScene/bt-denglu.png",0)
btnLogin:loadTextureDisabled("LaunchScene/bt-denglu.png",0)
btnLogin:setTitleFontName("")
btnLogin:setTitleFontSize(36)
btnLogin:setTitleColor({r = 255, g = 165, b = 0})
btnLogin:setLayoutComponentEnabled(true)
btnLogin:setName("btnLogin")
btnLogin:setTag(221)
btnLogin:setCascadeColorEnabled(true)
btnLogin:setCascadeOpacityEnabled(true)
btnLogin:setPosition(1089.9350, 120.0045)
layout = ccui.LayoutComponent:bindLayoutComponent(btnLogin)
layout:setPositionPercentX(0.8515)
layout:setPositionPercentY(0.1667)
layout:setPercentWidth(0.1961)
layout:setPercentHeight(0.1056)
layout:setSize({width = 251.0000, height = 76.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(964.4353)
layout:setRightMargin(64.5647)
layout:setTopMargin(561.9955)
layout:setBottomMargin(82.0045)
Layer:addChild(btnLogin)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("font/DFYuanW7-GB2312.ttf")
Text_1:setFontSize(20)
Text_1:setString([[抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防受骗上当。适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活。]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(263)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(640.0000, 13.3118)
Text_1:setTextColor({r = 222, g = 246, b = 247})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0185)
layout:setPercentWidth(0.8680)
layout:setPercentHeight(0.0319)
layout:setSize({width = 1111.0000, height = 23.0000})
layout:setLeftMargin(84.5000)
layout:setRightMargin(84.5000)
layout:setTopMargin(695.1882)
layout:setBottomMargin(1.8118)
Layer:addChild(Text_1)

--Create btnWechatLogin
local btnWechatLogin = ccui.Button:create()
btnWechatLogin:ignoreContentAdaptWithSize(false)
btnWechatLogin:loadTextureNormal("LaunchScene/bt-weixingdenglu.png",0)
btnWechatLogin:loadTexturePressed("LaunchScene/bt-weixingdenglu.png",0)
btnWechatLogin:loadTextureDisabled("LaunchScene/bt-weixingdenglu.png",0)
btnWechatLogin:setTitleFontSize(14)
btnWechatLogin:setTitleColor({r = 65, g = 65, b = 70})
btnWechatLogin:setScale9Enabled(true)
btnWechatLogin:setCapInsets({x = 15, y = 11, width = 271, height = 70})
btnWechatLogin:setLayoutComponentEnabled(true)
btnWechatLogin:setName("btnWechatLogin")
btnWechatLogin:setTag(53)
btnWechatLogin:setCascadeColorEnabled(true)
btnWechatLogin:setCascadeOpacityEnabled(true)
btnWechatLogin:setPosition(641.5677, 107.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnWechatLogin)
layout:setPositionPercentX(0.5012)
layout:setPositionPercentY(0.1486)
layout:setPercentWidth(0.2352)
layout:setPercentHeight(0.1278)
layout:setSize({width = 301.0000, height = 92.0000})
layout:setLeftMargin(491.0677)
layout:setRightMargin(487.9323)
layout:setTopMargin(567.0000)
layout:setBottomMargin(61.0000)
Layer:addChild(btnWechatLogin)

--Create Sprite_2
local Sprite_2 = cc.Sprite:create("LaunchScene/bg-huangganmajiang2.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(146)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(642.4720, 194.3074)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.2699)
layout:setPercentWidth(0.6359)
layout:setPercentHeight(0.0569)
layout:setSize({width = 814.0000, height = 41.0000})
layout:setLeftMargin(235.4720)
layout:setRightMargin(230.5281)
layout:setTopMargin(505.1926)
layout:setBottomMargin(173.8074)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

