--[[
Auto generated file by excel
主码：0--9为缺省系统命令码，不可用
MC: 客户端发送给服务端消息码
MS: 服务端发送给客户端消息码
--]]
CMD_HOTFIX = {}
CMD_HOTFIX.MAIN = 10000 --[pb: MC: 无, MS: 无]
CMD_HOTFIX.SUB_HOTFIX_WORK = 1 --[pb: MC: 无, MS: 无]
CMD_HOTFIX.SUB_HOTFIX_DB = 2 --[pb: MC: 无, MS: 无]

CMD_ERR = {}
CMD_ERR.MAIN = 20000 --[pb: MC: 无, MS: 无]
CMD_ERR.SUB_ERR_MS_ERR = 1 --[pb: MC: 无, MS: 无]

CMD_LOGON = {}
CMD_LOGON.MAIN = 10 --[pb: MC: 无, MS: 无]
CMD_LOGON.SUB_LOGON_USERID =  101

CMD_LOGON.SUB_LOGON_RES = 1001
CMD_LOGON.SUB_LOGON_FINISH = 1010 --登陆完成,[pb: MC: 无, MS: 无]

CMD_USER = {}
CMD_USER.MAIN = 15 --[pb: MC: 无, MS: 无]
CMD_USER.SUB_MC_TABLE_CREATE = 1 --创建
CMD_USER.SUB_MC_TABLE_JOIN = 2 --加入桌子
CMD_USER.SUB_MC_LOCATION = 3--用户定位信息

CMD_USER.SUB_MS_TABLE_CREATE = 12
CMD_USER.SUB_MS_TABLE_JOIN = 13

CMD_USER.SUB_MS_TABLE_INFO = 102    --桌子的普通信息

CMD_USER.SUB_MS_WEALTH_CHANGE = 201 --玩家财富改变
CMD_USER.SUB_MS_STATUS_CHANGE = 202 --玩家状态改变

CMD_GF_FRAME = {}
CMD_GF_FRAME.MAIN = 100
CMD_GF_FRAME.MC_GAMESCENE_LOAD_FINISH = 1  --桌子场景载入完毕
CMD_GF_FRAME.MC_USER_READY = 2  --玩家举手准备
CMD_GF_FRAME.MC_STAND_UP = 3    --非房主玩家起立
CMD_GF_FRAME.MC_DISMISS = 4 --解散房间

CMD_GF_FRAME.MCMS_TABLE_TALK = 11

CMD_GF_FRAME.MS_DISMISS = 101
CMD_GF_FRAME.MS_DISMISS_CONFIRM = 102
CMD_GF_FRAME.MS_DISMISS_FAIL = 103

CMD_GF_FRAME.MS_LOCATION = 105
CMD_GF_FRAME.MS_CHEATERES_CONFIRM = 106 --检查到可能有作弊玩家，通知玩家是否继续游戏

CMD_GF_FRAME.MS_USER_SITDOWN = 111
CMD_GF_FRAME.MS_USER_READY = 112
CMD_GF_FRAME.MS_STAND_UP = 113
CMD_GF_FRAME.MS_USER_OFFLINE = 114
CMD_GF_FRAME.MS_USER_RECONNECT = 115


MDM_GF_GAME = {}
MDM_GF_GAME.MAIN = 200

CMD_TEST = {}
CMD_TEST.MAIN = 10000 --[pb: MC: 无, MS: 无]
CMD_TEST.SUB_TEST_REQ = 1 --[pb: MC: 无, MS: 无]
CMD_TEST.SUB_TEST_RES = 100 --[pb: MC: 无, MS: 无]

