--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("GameScene/bg-touxiangkuan3.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(151)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(0.5876, -21.8943)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 96.0000, height = 124.0000})
layout:setLeftMargin(-47.4124)
layout:setRightMargin(-48.5876)
layout:setTopMargin(-40.1057)
layout:setBottomMargin(-83.8943)
Node:addChild(Image_1)

--Create btnHead
local btnHead = ccui.Button:create()
btnHead:ignoreContentAdaptWithSize(false)
btnHead:loadTextureNormal("GameScene/bg-touxiangkuan2.png",0)
btnHead:loadTexturePressed("GameScene/bg-touxiangkuan2.png",0)
btnHead:loadTextureDisabled("Default/Button_Disable.png",0)
btnHead:setTitleFontSize(14)
btnHead:setTitleColor({r = 65, g = 65, b = 70})
btnHead:setScale9Enabled(true)
btnHead:setCapInsets({x = 15, y = 11, width = 66, height = 74})
btnHead:setLayoutComponentEnabled(true)
btnHead:setName("btnHead")
btnHead:setTag(145)
btnHead:setCascadeColorEnabled(true)
btnHead:setCascadeOpacityEnabled(true)
btnHead:setPosition(0.6369, -9.0307)
layout = ccui.LayoutComponent:bindLayoutComponent(btnHead)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(-44.3631)
layout:setRightMargin(-45.6369)
layout:setTopMargin(-35.9693)
layout:setBottomMargin(-54.0307)
Node:addChild(btnHead)

--Create imgFrame
local imgFrame = ccui.ImageView:create()
imgFrame:ignoreContentAdaptWithSize(false)
imgFrame:loadTexture("GameScene/bg-touxiangkuan.png",0)
imgFrame:setScale9Enabled(true)
imgFrame:setCapInsets({x = 20, y = 17, width = 75, height = 104})
imgFrame:setLayoutComponentEnabled(true)
imgFrame:setName("imgFrame")
imgFrame:setTag(146)
imgFrame:setCascadeColorEnabled(true)
imgFrame:setCascadeOpacityEnabled(true)
imgFrame:setPosition(44.3709, 42.4807)
layout = ccui.LayoutComponent:bindLayoutComponent(imgFrame)
layout:setPositionPercentX(0.4930)
layout:setPositionPercentY(0.4720)
layout:setPercentWidth(1.1778)
layout:setPercentHeight(1.1778)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-8.6291)
layout:setRightMargin(-7.3709)
layout:setTopMargin(-5.4807)
layout:setBottomMargin(-10.5193)
btnHead:addChild(imgFrame)

--Create spZhuang
local spZhuang = cc.Sprite:create("GameScene/bg-zhuang.png")
spZhuang:setName("spZhuang")
spZhuang:setTag(147)
spZhuang:setCascadeColorEnabled(true)
spZhuang:setCascadeOpacityEnabled(true)
spZhuang:setPosition(44.4035, 111.7230)
layout = ccui.LayoutComponent:bindLayoutComponent(spZhuang)
layout:setPositionPercentX(0.4934)
layout:setPositionPercentY(1.2414)
layout:setPercentWidth(0.8000)
layout:setPercentHeight(0.8333)
layout:setSize({width = 72.0000, height = 75.0000})
layout:setLeftMargin(8.4035)
layout:setRightMargin(9.5965)
layout:setTopMargin(-59.2230)
layout:setBottomMargin(74.2230)
spZhuang:setBlendFunc({src = 1, dst = 771})
btnHead:addChild(spZhuang)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("GameScene/bg-touxiangkuan4.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(148)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(44.2934, -18.1258)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.4921)
layout:setPositionPercentY(-0.2014)
layout:setPercentWidth(1.1111)
layout:setPercentHeight(0.3000)
layout:setSize({width = 100.0000, height = 27.0000})
layout:setLeftMargin(-5.7066)
layout:setRightMargin(-4.2934)
layout:setTopMargin(94.6258)
layout:setBottomMargin(-31.6258)
btnHead:addChild(Image_2)

--Create lblName
local lblName = ccui.Text:create()
lblName:ignoreContentAdaptWithSize(true)
lblName:setTextAreaSize({width = 0, height = 0})
lblName:setFontName("font/DFYuanW7-GB2312.ttf")
lblName:setFontSize(24)
lblName:setString([[wakaka]])
lblName:setLayoutComponentEnabled(true)
lblName:setName("lblName")
lblName:setTag(149)
lblName:setCascadeColorEnabled(true)
lblName:setCascadeOpacityEnabled(true)
lblName:setPosition(43.7429, -18.9359)
lblName:setTextColor({r = 84, g = 46, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(lblName)
layout:setPositionPercentX(0.4860)
layout:setPositionPercentY(-0.2104)
layout:setPercentWidth(0.8222)
layout:setPercentHeight(0.3000)
layout:setSize({width = 74.0000, height = 27.0000})
layout:setLeftMargin(6.7429)
layout:setRightMargin(9.2571)
layout:setTopMargin(95.4359)
layout:setBottomMargin(-32.4359)
btnHead:addChild(lblName)

--Create imgFans
local imgFans = ccui.ImageView:create()
imgFans:ignoreContentAdaptWithSize(false)
imgFans:loadTexture("GameScene/bg-beisu.png",0)
imgFans:setLayoutComponentEnabled(true)
imgFans:setName("imgFans")
imgFans:setTag(142)
imgFans:setCascadeColorEnabled(true)
imgFans:setCascadeOpacityEnabled(true)
imgFans:setPosition(46.7991, 22.7011)
layout = ccui.LayoutComponent:bindLayoutComponent(imgFans)
layout:setSize({width = 66.0000, height = 34.0000})
layout:setLeftMargin(13.7991)
layout:setRightMargin(-79.7991)
layout:setTopMargin(-39.7011)
layout:setBottomMargin(5.7011)
Node:addChild(imgFans)

--Create txtFans
local txtFans = ccui.Text:create()
txtFans:ignoreContentAdaptWithSize(true)
txtFans:setTextAreaSize({width = 0, height = 0})
txtFans:setFontName("font/DFYuanW7-GB2312.ttf")
txtFans:setFontSize(18)
txtFans:setString([[12番]])
txtFans:setLayoutComponentEnabled(true)
txtFans:setName("txtFans")
txtFans:setTag(143)
txtFans:setCascadeColorEnabled(true)
txtFans:setCascadeOpacityEnabled(true)
txtFans:setPosition(32.2172, 16.5136)
txtFans:setTextColor({r = 84, g = 46, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txtFans)
layout:setPositionPercentX(0.4881)
layout:setPositionPercentY(0.4857)
layout:setPercentWidth(0.5909)
layout:setPercentHeight(0.6176)
layout:setSize({width = 39.0000, height = 21.0000})
layout:setLeftMargin(12.7172)
layout:setRightMargin(14.2828)
layout:setTopMargin(6.9864)
layout:setBottomMargin(6.0136)
imgFans:addChild(txtFans)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

