--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panRoot
local panRoot = ccui.Layout:create()
panRoot:ignoreContentAdaptWithSize(false)
panRoot:setClippingEnabled(false)
panRoot:setBackGroundColorType(1)
panRoot:setBackGroundColor({r = 150, g = 200, b = 255})
panRoot:setBackGroundColorOpacity(102)
panRoot:setTouchEnabled(true);
panRoot:setLayoutComponentEnabled(true)
panRoot:setName("panRoot")
panRoot:setTag(234)
panRoot:setCascadeColorEnabled(true)
panRoot:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panRoot)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setRightMargin(-200.0000)
layout:setTopMargin(-200.0000)
Node:addChild(panRoot)

--Create imgCard
local imgCard = cc.Sprite:create("GameScene/vertical/mingmah_11.png")
imgCard:setName("imgCard")
imgCard:setTag(204)
imgCard:setCascadeColorEnabled(true)
imgCard:setCascadeOpacityEnabled(true)
imgCard:setPosition(-368.3987, 219.5962)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard)
layout:setPositionPercentX(-1.8420)
layout:setPositionPercentY(1.0980)
layout:setPercentWidth(0.4450)
layout:setPercentHeight(0.6750)
layout:setSize({width = 89.0000, height = 135.0000})
layout:setLeftMargin(-412.8987)
layout:setRightMargin(523.8987)
layout:setTopMargin(-87.0962)
layout:setBottomMargin(152.0962)
imgCard:setBlendFunc({src = 1, dst = 771})
panRoot:addChild(imgCard)

--Create btnHu
local btnHu = ccui.Button:create()
btnHu:ignoreContentAdaptWithSize(false)
btnHu:loadTextureNormal("GameScene/bt-hu.png",0)
btnHu:loadTexturePressed("GameScene/bt-hu.png",0)
btnHu:loadTextureDisabled("Default/Button_Disable.png",0)
btnHu:setTitleFontSize(14)
btnHu:setTitleColor({r = 65, g = 65, b = 70})
btnHu:setScale9Enabled(true)
btnHu:setCapInsets({x = 15, y = 11, width = 73, height = 81})
btnHu:setLayoutComponentEnabled(true)
btnHu:setName("btnHu")
btnHu:setTag(205)
btnHu:setCascadeColorEnabled(true)
btnHu:setCascadeOpacityEnabled(true)
btnHu:setPosition(-510.6042, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnHu)
layout:setPositionPercentX(-2.5530)
layout:setPositionPercentY(0.3327)
layout:setPercentWidth(0.5150)
layout:setPercentHeight(0.5150)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(-562.1042)
layout:setRightMargin(659.1042)
layout:setTopMargin(81.9583)
layout:setBottomMargin(15.0417)
panRoot:addChild(btnHu)

--Create btnGang
local btnGang = ccui.Button:create()
btnGang:ignoreContentAdaptWithSize(false)
btnGang:loadTextureNormal("GameScene/bt-gang.png",0)
btnGang:loadTexturePressed("GameScene/bt-gang.png",0)
btnGang:loadTextureDisabled("Default/Button_Disable.png",0)
btnGang:setTitleFontSize(14)
btnGang:setTitleColor({r = 65, g = 65, b = 70})
btnGang:setScale9Enabled(true)
btnGang:setCapInsets({x = 15, y = 11, width = 73, height = 81})
btnGang:setLayoutComponentEnabled(true)
btnGang:setName("btnGang")
btnGang:setTag(206)
btnGang:setCascadeColorEnabled(true)
btnGang:setCascadeOpacityEnabled(true)
btnGang:setPosition(-664.1604, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnGang)
layout:setPositionPercentX(-3.3208)
layout:setPositionPercentY(0.3327)
layout:setPercentWidth(0.5150)
layout:setPercentHeight(0.5150)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(-715.6604)
layout:setRightMargin(812.6604)
layout:setTopMargin(81.9583)
layout:setBottomMargin(15.0417)
panRoot:addChild(btnGang)

--Create btnChi
local btnChi = ccui.Button:create()
btnChi:ignoreContentAdaptWithSize(false)
btnChi:loadTextureNormal("GameScene/bt-chi.png",0)
btnChi:loadTexturePressed("GameScene/bt-chi.png",0)
btnChi:loadTextureDisabled("Default/Button_Disable.png",0)
btnChi:setTitleFontSize(14)
btnChi:setTitleColor({r = 65, g = 65, b = 70})
btnChi:setScale9Enabled(true)
btnChi:setCapInsets({x = 15, y = 11, width = 73, height = 81})
btnChi:setLayoutComponentEnabled(true)
btnChi:setName("btnChi")
btnChi:setTag(207)
btnChi:setCascadeColorEnabled(true)
btnChi:setCascadeOpacityEnabled(true)
btnChi:setPosition(-357.0481, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnChi)
layout:setPositionPercentX(-1.7852)
layout:setPositionPercentY(0.3327)
layout:setPercentWidth(0.5150)
layout:setPercentHeight(0.5150)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(-408.5481)
layout:setRightMargin(505.5481)
layout:setTopMargin(81.9583)
layout:setBottomMargin(15.0417)
panRoot:addChild(btnChi)

--Create btnPeng
local btnPeng = ccui.Button:create()
btnPeng:ignoreContentAdaptWithSize(false)
btnPeng:loadTextureNormal("GameScene/bt-peng.png",0)
btnPeng:loadTexturePressed("GameScene/bt-peng.png",0)
btnPeng:loadTextureDisabled("Default/Button_Disable.png",0)
btnPeng:setTitleFontSize(14)
btnPeng:setTitleColor({r = 65, g = 65, b = 70})
btnPeng:setScale9Enabled(true)
btnPeng:setCapInsets({x = 15, y = 11, width = 73, height = 81})
btnPeng:setLayoutComponentEnabled(true)
btnPeng:setName("btnPeng")
btnPeng:setTag(208)
btnPeng:setCascadeColorEnabled(true)
btnPeng:setCascadeOpacityEnabled(true)
btnPeng:setPosition(-203.4919, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPeng)
layout:setPositionPercentX(-1.0175)
layout:setPositionPercentY(0.3327)
layout:setPercentWidth(0.5150)
layout:setPercentHeight(0.5150)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(-254.9919)
layout:setRightMargin(351.9919)
layout:setTopMargin(81.9583)
layout:setBottomMargin(15.0417)
panRoot:addChild(btnPeng)

--Create btnGuo
local btnGuo = ccui.Button:create()
btnGuo:ignoreContentAdaptWithSize(false)
btnGuo:loadTextureNormal("GameScene/bt-guo.png",0)
btnGuo:loadTexturePressed("GameScene/bt-guo.png",0)
btnGuo:loadTextureDisabled("Default/Button_Disable.png",0)
btnGuo:setTitleFontSize(14)
btnGuo:setTitleColor({r = 65, g = 65, b = 70})
btnGuo:setScale9Enabled(true)
btnGuo:setCapInsets({x = 15, y = 11, width = 73, height = 81})
btnGuo:setLayoutComponentEnabled(true)
btnGuo:setName("btnGuo")
btnGuo:setTag(209)
btnGuo:setCascadeColorEnabled(true)
btnGuo:setCascadeOpacityEnabled(true)
btnGuo:setPosition(-49.9358, 66.5417)
layout = ccui.LayoutComponent:bindLayoutComponent(btnGuo)
layout:setPositionPercentX(-0.2497)
layout:setPositionPercentY(0.3327)
layout:setPercentWidth(0.5150)
layout:setPercentHeight(0.5150)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(-101.4358)
layout:setRightMargin(198.4358)
layout:setTopMargin(81.9583)
layout:setBottomMargin(15.0417)
panRoot:addChild(btnGuo)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

