
--[[*******************************************************
 * 
 * This file is auto generated by config export tool,
 * please DO NOT edit it
 * 
 ********************************************************]]
 --[[

rolls:	房间局数
need_room_cards:	消耗房卡数量

 ]]
return 
{
    [8] = 
        {
            ["need_room_cards"] = 1,
            ["rolls"] = 8,
        },
    [16] = 
        {
            ["need_room_cards"] = 2,
            ["rolls"] = 16,
        },
}
