return {
	need_fight = 3000,--需求战斗力(必填)
	need_radom_rates = {{1.9,2.1},{14,16},{1.9,2.1},{199,201}},--指定随机权重(必填)(顺序依次为装备升级、装备升阶、技能升级、技能升阶)
	need_hero_occ = 1001,--指定职业
	need_hero_equ_fine = nil,--指定装精
	need_all_equ_lv = nil,--需求总装等
	need_all_skill_degree = nil, --需求技能总小阶数
	need_equ_com_rate = {0.8,1}, --需求装备齐备率
	need_skill_com_rate = {0.7,1}, --需求技能齐备率
	create_hero_count = 10, --创建机器人个数
	arena_robots = {  --not_repeat = true
	
		{ rank = 1000, fight = 265, recommend_fight = 1325, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1020, fight = 441, recommend_fight = 2205, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1040, fight = 617, recommend_fight = 3085, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1060, fight = 792, recommend_fight = 3960, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1080, fight = 968, recommend_fight = 4840, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1100, fight = 1144, recommend_fight = 5720, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1120, fight = 1453, recommend_fight = 7265, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1140, fight = 1763, recommend_fight = 8815, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1160, fight = 2072, recommend_fight = 10360, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1180, fight = 2382, recommend_fight = 11910, num = 1, occno = 4,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1200, fight = 2691, recommend_fight = 13455, num = 1, occno = 6,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1220, fight = 3141, recommend_fight = 15705, num = 1, occno = 6,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1240, fight = 3590, recommend_fight = 17950, num = 1, occno = 6,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1260, fight = 4040, recommend_fight = 20200, num = 1, occno = 6,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1280, fight = 4489, recommend_fight = 22445, num = 1, occno = 6,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1300, fight = 4938, recommend_fight = 24690, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1320, fight = 5532, recommend_fight = 27660, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1340, fight = 6126, recommend_fight = 30630, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1360, fight = 6720, recommend_fight = 33600, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1380, fight = 7314, recommend_fight = 36570, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1400, fight = 7908, recommend_fight = 39540, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1420, fight = 8650, recommend_fight = 43250, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1440, fight = 9392, recommend_fight = 46960, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1460, fight = 10134, recommend_fight = 50670, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1480, fight = 10876, recommend_fight = 54380, num = 1, occno = 7,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1500, fight = 11618, recommend_fight = 58090, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1520, fight = 12512, recommend_fight = 62560, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1540, fight = 13405, recommend_fight = 67025, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1560, fight = 14298, recommend_fight = 71490, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1580, fight = 15191, recommend_fight = 75955, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1600, fight = 16084, recommend_fight = 80420, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1620, fight = 17131, recommend_fight = 85655, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1640, fight = 18178, recommend_fight = 90890, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1660, fight = 19225, recommend_fight = 96125, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1680, fight = 20272, recommend_fight = 101360, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1700, fight = 21319, recommend_fight = 106595, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1720, fight = 22522, recommend_fight = 112610, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1740, fight = 23725, recommend_fight = 118625, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1760, fight = 24928, recommend_fight = 124640, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1780, fight = 26131, recommend_fight = 130655, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1800, fight = 27334, recommend_fight = 136670, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1820, fight = 28695, recommend_fight = 143475, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1840, fight = 30056, recommend_fight = 150280, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1860, fight = 31417, recommend_fight = 157085, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1880, fight = 32778, recommend_fight = 163890, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1900, fight = 34139, recommend_fight = 170695, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1920, fight = 35660, recommend_fight = 178300, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1940, fight = 37180, recommend_fight = 185900, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1960, fight = 38701, recommend_fight = 193505, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 1980, fight = 40222, recommend_fight = 201110, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2000, fight = 41743, recommend_fight = 208715, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2020, fight = 43426, recommend_fight = 217130, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2040, fight = 45108, recommend_fight = 225540, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2060, fight = 46791, recommend_fight = 233955, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2080, fight = 48473, recommend_fight = 242365, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2100, fight = 50155, recommend_fight = 250775, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2120, fight = 52001, recommend_fight = 260005, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2140, fight = 53847, recommend_fight = 269235, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2160, fight = 55692, recommend_fight = 278460, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2180, fight = 57538, recommend_fight = 287690, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2200, fight = 59384, recommend_fight = 296920, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2220, fight = 61394, recommend_fight = 306970, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2240, fight = 63404, recommend_fight = 317020, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2260, fight = 65414, recommend_fight = 327070, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2280, fight = 67424, recommend_fight = 337120, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2300, fight = 69435, recommend_fight = 347175, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2320, fight = 71611, recommend_fight = 358055, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2340, fight = 73787, recommend_fight = 368935, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2360, fight = 75963, recommend_fight = 379815, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2380, fight = 78139, recommend_fight = 390695, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2400, fight = 80315, recommend_fight = 401575, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2420, fight = 82659, recommend_fight = 413295, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2440, fight = 85002, recommend_fight = 425010, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2460, fight = 87345, recommend_fight = 436725, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2480, fight = 89689, recommend_fight = 448445, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2500, fight = 92032, recommend_fight = 460160, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2520, fight = 94544, recommend_fight = 472720, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2540, fight = 97056, recommend_fight = 485280, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2560, fight = 99567, recommend_fight = 497835, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2580, fight = 102079, recommend_fight = 510395, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2600, fight = 104591, recommend_fight = 522955, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2620, fight = 107272, recommend_fight = 536360, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2640, fight = 109953, recommend_fight = 549765, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2660, fight = 112634, recommend_fight = 563170, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2680, fight = 115316, recommend_fight = 576580, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2700, fight = 117997, recommend_fight = 589985, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2720, fight = 120849, recommend_fight = 604245, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2740, fight = 123701, recommend_fight = 618505, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2760, fight = 126552, recommend_fight = 632760, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2780, fight = 129404, recommend_fight = 647020, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2800, fight = 132256, recommend_fight = 661280, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2820, fight = 135280, recommend_fight = 676400, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2840, fight = 138303, recommend_fight = 691515, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2860, fight = 141327, recommend_fight = 706635, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2880, fight = 144350, recommend_fight = 721750, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2900, fight = 147373, recommend_fight = 736865, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2920, fight = 150569, recommend_fight = 752845, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2940, fight = 153765, recommend_fight = 768825, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2960, fight = 156962, recommend_fight = 784810, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 2980, fight = 160158, recommend_fight = 800790, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3000, fight = 163354, recommend_fight = 816770, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3020, fight = 166723, recommend_fight = 833615, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3040, fight = 170093, recommend_fight = 850465, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3060, fight = 173462, recommend_fight = 867310, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3080, fight = 176832, recommend_fight = 884160, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3100, fight = 180201, recommend_fight = 901005, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3120, fight = 183745, recommend_fight = 918725, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3140, fight = 187289, recommend_fight = 936445, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3160, fight = 190833, recommend_fight = 954165, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3180, fight = 194377, recommend_fight = 971885, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3200, fight = 197921, recommend_fight = 989605, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3220, fight = 201640, recommend_fight = 1008200, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3240, fight = 205359, recommend_fight = 1026795, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3260, fight = 209078, recommend_fight = 1045390, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3280, fight = 212798, recommend_fight = 1063990, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3300, fight = 216517, recommend_fight = 1082585, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3320, fight = 220412, recommend_fight = 1102060, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3340, fight = 224307, recommend_fight = 1121535, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3360, fight = 228203, recommend_fight = 1141015, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3380, fight = 232098, recommend_fight = 1160490, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3400, fight = 235993, recommend_fight = 1179965, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3420, fight = 240065, recommend_fight = 1200325, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3440, fight = 244137, recommend_fight = 1220685, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3460, fight = 248209, recommend_fight = 1241045, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3480, fight = 252282, recommend_fight = 1261410, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3500, fight = 256354, recommend_fight = 1281770, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3520, fight = 260603, recommend_fight = 1303015, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3540, fight = 264853, recommend_fight = 1324265, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3560, fight = 269103, recommend_fight = 1345515, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3580, fight = 273353, recommend_fight = 1366765, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3600, fight = 277603, recommend_fight = 1388015, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3620, fight = 282031, recommend_fight = 1410155, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3640, fight = 286459, recommend_fight = 1432295, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3660, fight = 290887, recommend_fight = 1454435, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3680, fight = 295315, recommend_fight = 1476575, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },
		{ rank = 3700, fight = 299743, recommend_fight = 1498715, num = 1, occno = 8,have_pet = true,pet_id = nil, weapons = nil,not_repeat = false },










	



	




	},
			battlefield_robots = {
		{ fight = 500, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 509, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 518, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 527, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 536, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 545, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 554, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 563, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 573, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 583, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 593, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 603, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 613, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 623, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 634, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 645, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 656, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 667, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 678, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 690, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 702, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 714, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 726, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 738, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 751, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 764, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 777, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 790, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 804, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 818, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 832, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 846, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 860, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 875, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 890, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 905, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 920, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 936, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 952, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 968, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 985, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1002, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1019, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1036, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1054, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1072, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1090, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1109, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1128, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1147, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1167, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1187, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1207, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1228, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1249, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1270, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1292, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1314, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1336, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1359, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1382, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1406, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1430, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1454, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1479, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1504, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1530, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1556, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1583, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1610, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1638, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1666, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1695, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1724, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1754, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1784, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1815, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1846, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1878, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1910, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1943, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 1976, num = 10, occno = 4,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2010, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2044, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2079, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2115, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2151, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2188, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2225, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2263, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2302, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2341, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2381, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2422, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2463, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2505, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2548, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2592, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2636, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2681, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2727, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2774, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2821, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2869, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2918, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 2968, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3019, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3071, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3124, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3177, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3231, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3286, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3342, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3399, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3457, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3516, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3576, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3637, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3699, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3762, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3826, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3892, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 3959, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4027, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4096, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4166, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4237, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4310, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4384, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4459, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4535, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4613, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4692, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4772, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4854, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 4937, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5022, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5108, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5195, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5284, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5374, num = 10, occno = 5,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5466, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5560, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5655, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5752, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5850, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 5950, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6052, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6156, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6261, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6368, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6477, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6588, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6701, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6816, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 6933, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7052, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7173, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7296, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7421, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7548, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7677, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7808, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 7942, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8078, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8216, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8357, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8500, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8646, num = 10, occno = 6,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8794, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 8945, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9098, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9254, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9412, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9573, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9737, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 9904, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10074, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10246, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10421, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10599, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10780, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 10965, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 11153, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 11344, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 11538, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 11736, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 11937, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 12141, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 12349, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 12560, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 12775, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 12994, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 13216, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 13442, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 13672, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 13906, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 14144, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 14386, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 14632, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 14883, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 15138, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 15397, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 15661, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 15929, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 16202, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 16479, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 16761, num = 10, occno = 7,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 17048, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 17340, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 17637, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 17939, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 18246, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 18558, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 18876, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 19199, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 19528, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 19862, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 20202, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 20548, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 20900, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 21258, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 21622, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 21992, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 22369, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 22752, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 23142, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 23538, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 23941, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 24351, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 24768, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 25192, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 25623, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 26062, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 26508, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 26962, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 27424, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 27894, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 28372, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 28858, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 29352, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 29855, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 30366, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 30886, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 31415, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 31953, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 32500, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 33056, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 33622, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 34198, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 34783, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 35378, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 35984, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 36600, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 37227, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 37864, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 38512, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 39171, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 39842, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 40524, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 41218, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 41924, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 42642, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 43372, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 44115, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 44870, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 45638, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 46419, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 47214, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 48022, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 48844, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 49680, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 50531, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 51396, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 52276, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 53171, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 54081, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 55007, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 55949, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 56907, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 57881, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 58872, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 59880, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 60905, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 61948, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 63009, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 64088, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 65185, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 66301, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 67436, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 68591, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 69765, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 70959, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 72174, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 73410, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 74667, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 75945, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 77245, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 78567, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 79912, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 81280, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 82672, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 84087, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 85527, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 86991, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 88480, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 89995, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 91536, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 93103, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 94697, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 96318, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 97967, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 99644, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 101350, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 103085, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 104850, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 106645, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 108471, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 110328, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 112217, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 114138, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 116092, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 118080, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 120102, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 122158, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 124249, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 126376, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 128540, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 130741, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 132979, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 135256, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 137572, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 139927, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 142323, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 144760, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 147238, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 149759, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 152323, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 154931, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 157583, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 160281, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 163025, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 165816, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 168655, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 171542, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 174479, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 177466, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 180504, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 183594, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 186737, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 189934, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 193186, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 196493, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 199857, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 203279, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 206759, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 210299, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 213899, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 217561, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 221286, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 225074, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 228927, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 232846, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 236832, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 240887, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 245011, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 249206, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 253472, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 257811, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 262225, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 266714, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 271280, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 275924, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 280648, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 285453, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 290340, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },
		{ fight = 295311, num = 10, occno = 8,have_pet = true,pet_id = nil, weapons = nil },












	},
}