
--[[*******************************************************
 * 
 * This file is auto generated by config export tool,
 * please DO NOT edit it
 * 
 ********************************************************]]
 --[[

id:	道具商城id
name:	名称
moneydisplay:	费用显示
icon:	图标
price:	费用
roomcard:	房卡
bindingdisplay:	是否绑定后显示
display:	是否显示

 ]]
return 
{
    [1] = 
        {
            ["moneydisplay"] = "3元",
            ["name"] = "3张房卡",
            ["price"] = 3,
            ["bindingdisplay"] = false,
            ["display"] = true,
            ["icon"] = "0",
            ["id"] = 1,
            ["roomcard"] = 3,
        },
    [2] = 
        {
            ["moneydisplay"] = "12元",
            ["name"] = "12张房卡",
            ["price"] = 12,
            ["bindingdisplay"] = false,
            ["display"] = true,
            ["icon"] = "0",
            ["id"] = 2,
            ["roomcard"] = 12,
        },
    [3] = 
        {
            ["moneydisplay"] = "30元",
            ["name"] = "30张房卡",
            ["price"] = 30,
            ["bindingdisplay"] = false,
            ["display"] = true,
            ["icon"] = "0",
            ["id"] = 3,
            ["roomcard"] = 30,
        },
    [4] = 
        {
            ["moneydisplay"] = "100元",
            ["name"] = "100张房卡",
            ["price"] = 100,
            ["bindingdisplay"] = false,
            ["display"] = true,
            ["icon"] = "0",
            ["id"] = 4,
            ["roomcard"] = 100,
        },
    [5] = 
        {
            ["moneydisplay"] = "1000元",
            ["name"] = "1000张房卡",
            ["price"] = 1000,
            ["bindingdisplay"] = true,
            ["display"] = true,
            ["icon"] = "0",
            ["id"] = 5,
            ["roomcard"] = 1000,
        },
}
